import { test, expect, waitForAppReady, checkForErrorPage, screenshot } from './helpers/electronApp'

test.describe('Coding Agent Demo — E2E', () => {
  test('Demo option appears in template selector', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    expect(templateSelect).not.toBeNull()

    const options = await templateSelect!.$$('option')
    const optionTexts: string[] = []
    for (const opt of options) {
      optionTexts.push(await opt.textContent() || '')
    }

    expect(optionTexts.some(t => t.includes('Coding Demo'))).toBe(true)
  })

  test('Run Coding Demo creates sandbox and starts preview', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    // Navigate to Preview
    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    // Select "Coding Demo" template
    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    await templateSelect!.selectOption({ label: 'Coding Demo' })
    await mainWindow.waitForTimeout(300)

    // Click "Create & Start Preview"
    const createBtn = await mainWindow.$('[data-testid="preview-create-btn"]')
    expect(createBtn).not.toBeNull()
    await createBtn!.click()

    // Wait for server to start (up to 10s)
    await mainWindow.waitForTimeout(4000)

    // Check for running status
    const statusEl = await mainWindow.$('[data-testid="preview-status"]')
    expect(statusEl).not.toBeNull()
    const statusText = await statusEl!.textContent()
    expect(statusText).toMatch(/Running|Starting/i)

    // Check URL is present
    const urlInput = await mainWindow.$('[data-testid="preview-url-input"]')
    expect(urlInput).not.toBeNull()
    const urlValue = await urlInput!.inputValue()
    expect(urlValue).toContain('http://127.0.0.1')

    expect(await checkForErrorPage(mainWindow)).toBeNull()

    await screenshot(mainWindow, 'coding-demo-preview')
  })

  test('Demo counter page loads with correct HTML content', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    // Select Coding Demo and start
    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    await templateSelect!.selectOption({ label: 'Coding Demo' })
    await mainWindow.waitForTimeout(300)
    await mainWindow.click('[data-testid="preview-create-btn"]')
    await mainWindow.waitForTimeout(4000)

    // Get the preview URL
    const urlInput = await mainWindow.$('[data-testid="preview-url-input"]')
    const urlValue = await urlInput!.inputValue()

    if (urlValue && urlValue.startsWith('http')) {
      // Navigate to the preview URL and verify content
      await mainWindow.goto(urlValue)
      await mainWindow.waitForTimeout(1000)

      const pageContent = await mainWindow.textContent('body')

      // Verify all required elements from the spec
      expect(pageContent).toContain('Vibeforge Counter Demo')
      expect(pageContent).toContain('Self-Test Coding Agent Demo')
      expect(pageContent).toContain('Increment')
      expect(pageContent).toContain('Reset')
      expect(pageContent).toContain('Generated by Vibeforge')

      // Verify counter starts at 0
      const counterText = await mainWindow.textContent('#counter')
      expect(counterText).toBe('0')

      // Click increment button
      await mainWindow.click('#btn-increment')
      await mainWindow.waitForTimeout(200)
      const counterAfterInc = await mainWindow.textContent('#counter')
      expect(counterAfterInc).toBe('1')

      // Click increment again
      await mainWindow.click('#btn-increment')
      await mainWindow.waitForTimeout(200)
      const counterAfter2 = await mainWindow.textContent('#counter')
      expect(counterAfter2).toBe('2')

      // Click reset
      await mainWindow.click('#btn-reset')
      await mainWindow.waitForTimeout(200)
      const counterAfterReset = await mainWindow.textContent('#counter')
      expect(counterAfterReset).toBe('0')

      await screenshot(mainWindow, 'coding-demo-counter-test')
    }

    expect(await checkForErrorPage(mainWindow)).toBeNull()
  })

  test('Stop button stops demo preview server', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    // Start demo
    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    await templateSelect!.selectOption({ label: 'Coding Demo' })
    await mainWindow.waitForTimeout(300)
    await mainWindow.click('[data-testid="preview-create-btn"]')
    await mainWindow.waitForTimeout(5000)

    // Click Stop
    const stopBtn = await mainWindow.$('[data-testid="preview-stop-btn"]')
    if (stopBtn) {
      await stopBtn.click()
      await mainWindow.waitForTimeout(1000)
    }

    // Status should change to stopped/idle
    const statusEl = await mainWindow.$('[data-testid="preview-status"]')
    const statusAfter = await statusEl!.textContent()
    expect(statusAfter).toMatch(/Stopped|Idle|Error/i)

    expect(await checkForErrorPage(mainWindow)).toBeNull()
  })

  test('Demo does not crash or leak secrets', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    // Start demo
    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    await templateSelect!.selectOption({ label: 'Coding Demo' })
    await mainWindow.waitForTimeout(300)
    await mainWindow.click('[data-testid="preview-create-btn"]')
    await mainWindow.waitForTimeout(5000)

    // Check log panel for any leaked secrets
    const logPanel = await mainWindow.$('[data-testid="preview-log-panel"]')
    if (logPanel) {
      const logText = await logPanel.textContent()
      // No API keys in logs
      expect(logText).not.toMatch(/sk-[a-zA-Z0-9]{20,}/)
      expect(logText).not.toMatch(/AIza[0-9A-Za-z_-]{20,}/)
    }

    expect(await checkForErrorPage(mainWindow)).toBeNull()
  })

  test('App handles rapid demo start/stop without crash', async ({ mainWindow }) => {
    await waitForAppReady(mainWindow)

    await mainWindow.click('[data-testid="nav-preview"]')
    await mainWindow.waitForTimeout(1000)

    // Start
    const templateSelect = await mainWindow.$('[data-testid="preview-template-select"]')
    await templateSelect!.selectOption({ label: 'Coding Demo' })
    await mainWindow.waitForTimeout(300)
    await mainWindow.click('[data-testid="preview-create-btn"]')
    await mainWindow.waitForTimeout(3000)

    // Stop
    const stopBtn = await mainWindow.$('[data-testid="preview-stop-btn"]')
    if (stopBtn) await stopBtn.click()
    await mainWindow.waitForTimeout(1000)

    // Start again
    const startBtn = await mainWindow.$('[data-testid="preview-start-btn"]')
    if (startBtn) {
      await startBtn.click()
      await mainWindow.waitForTimeout(3000)
    }

    // Stop again
    const stopBtn2 = await mainWindow.$('[data-testid="preview-stop-btn"]')
    if (stopBtn2) await stopBtn2.click()

    expect(await checkForErrorPage(mainWindow)).toBeNull()
  })
})
