import { v4 as uuid } from 'uuid'
import { app } from 'electron'
import path from 'path'
import fs from 'fs'
import http from 'http'
import { spawn, ChildProcess, execSync } from 'child_process'
import { logger } from '../utils/logger'
import { redactSecrets } from './log-redacter'

/**
 * LivePreview Service — safe local app preview for generated code.
 */

export interface PreviewSession {
  id: string
  sandboxPath: string
  sandboxUrl: string
  status: 'idle' | 'starting' | 'running' | 'error' | 'stopped'
  port: number
  process: ChildProcess | null
  logs: PreviewLogEntry[]
  templateType: string
  createdAt: string
  error: string | null
}

export interface PreviewLogEntry {
  timestamp: string
  stream: 'stdout' | 'stderr'
  text: string
}

export interface CreateSandboxInput {
  templateType?: string
  port?: number
  style?: string
}

export interface StartGeneratedPreviewInput {
  source: 'studio-build-app' | 'code-demo' | 'manual'
  files?: Record<string, string>
  entryFile?: string
  style?: string
  port?: number
  autoOpenCodeMode?: boolean
  autoFocusPreview?: boolean
}

export interface PreviewStatus {
  id: string | null
  status: 'idle' | 'starting' | 'running' | 'error' | 'stopped'
  sandboxPath: string | null
  url: string | null
  port: number | null
  templateType: string | null
  logs: PreviewLogEntry[]
  error: string | null
}

export interface CodingDemoResult {
  success: boolean
  sandboxId: string
  sandboxPath: string
  url: string | null
  filesWritten: string[]
  previewStatus: PreviewStatus
  error?: string
}

// ── Templates ──────────────────────────────────────────────────

/** Simple HTML counter — no frameworks, instant preview */
const SAMPLE_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Aureon Preview</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #FAF8F5; color: #2C2416; 
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; padding: 2rem;
    }
    .card {
      background: white; border-radius: 12px; padding: 2rem;
      box-shadow: 0 4px 24px rgba(44,36,22,0.08);
      max-width: 420px; width: 100%; text-align: center;
    }
    h1 { font-family: Georgia, 'Times New Roman', serif; font-size: 1.5rem; margin-bottom: 0.5rem; color: #C75B39; }
    p { color: #6B5E4A; line-height: 1.6; margin-bottom: 1rem; }
    button {
      background: #C75B39; color: white; border: none;
      padding: 0.5rem 1.5rem; border-radius: 8px; cursor: pointer;
      font-size: 0.875rem; transition: background 0.15s;
    }
    button:hover { background: #B04D2E; }
    button:active { transform: scale(0.98); }
    .counter { font-size: 2rem; font-weight: bold; color: #2C2416; margin: 1rem 0; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Aureon Preview</h1>
    <p>This is a live preview sandbox. Generated by Aureon Desk.</p>
    <div class="counter" id="count">0</div>
    <button onclick="document.getElementById('count').textContent = parseInt(document.getElementById('count').textContent) + 1">
      Click Me
    </button>
  </div>
</body>
</html>`

/** Coding Demo: "Vibeforge Counter Demo" — deterministic, no external APIs */
const DEMO_COUNTER_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vibeforge Counter Demo</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      background: #FAF8F5;
      color: #2C2416;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; padding: 2rem;
    }
    .card {
      background: white;
      border-radius: 16px;
      padding: 2.5rem;
      box-shadow: 0 4px 32px rgba(44,36,22,0.08);
      max-width: 400px; width: 100%; text-align: center;
    }
    h1 {
      font-size: 1.75rem;
      margin-bottom: 0.25rem;
      color: #C75B39;
      letter-spacing: -0.02em;
    }
    .subtitle {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.8rem;
      color: #8B7E6A;
      margin-bottom: 1.5rem;
      font-style: italic;
    }
    .counter {
      font-size: 3rem;
      font-weight: bold;
      color: #2C2416;
      margin: 1.25rem 0;
      font-variant-numeric: tabular-nums;
      transition: transform 0.15s ease;
      user-select: none;
    }
    .counter.bump { transform: scale(1.15); }
    .btn-row {
      display: flex; gap: 0.75rem; justify-content: center; flex-wrap: wrap;
    }
    .btn {
      border: none; border-radius: 8px;
      padding: 0.6rem 1.5rem; cursor: pointer;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.875rem; font-weight: 500;
      transition: background 0.15s, transform 0.1s;
    }
    .btn:active { transform: scale(0.97); }
    .btn-inc {
      background: #C75B39; color: white;
    }
    .btn-inc:hover { background: #B04D2E; }
    .btn-reset {
      background: #EDE4D8; color: #5C4A3A;
    }
    .btn-reset:hover { background: #D9CDBE; }
    .footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid #EDE4D8;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.7rem;
      color: #A89880;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>Vibeforge Counter Demo</h1>
    <p class="subtitle">Self-Test Coding Agent Demo</p>
    <div class="counter" id="counter">0</div>
    <div class="btn-row">
      <button class="btn btn-inc" id="btn-increment" onclick="increment()">Increment</button>
      <button class="btn btn-reset" id="btn-reset" onclick="reset()">Reset</button>
    </div>
    <p class="footer">Generated by Vibeforge</p>
  </div>
  <script>
    let count = 0;
    const counterEl = document.getElementById('counter');
    function increment() {
      count++;
      counterEl.textContent = count;
      counterEl.classList.add('bump');
      setTimeout(function() { counterEl.classList.remove('bump'); }, 150);
    }
    function reset() {
      count = 0;
      counterEl.textContent = count;
    }
  </script>
</body>
</html>`

// ── Helpers ─────────────────────────────────────────────────────

/**
 * Apply a visual style to demo HTML content by replacing color values.
 * Single source of truth — used by both createSandbox() and startGeneratedPreview().
 */
function applyStyleToHtml(html: string, style: string): string {
  if (style === 'Soft Teal') {
    return html
      .replace('background: #FAF8F5;', 'background: #F0F7F6;')
      .replace('color: #2C2416;', 'color: #1A2F2C;')
      .replace('color: #C75B39;', 'color: #2A8A7C;')
      .replace('background: #C75B39;', 'background: #2A8A7C;')
      .replace('background: #B04D2E;', 'background: #1F6B60;')
  }
  if (style === 'Deep Slate') {
    return html
      .replace('background: #FAF8F5;', 'background: #1E293B;')
      .replace('color: #2C2416;', 'color: #F1F5F9;')
      .replace('color: #C75B39;', 'color: #38BDF8;')
      .replace('background: #C75B39;', 'background: #38BDF8;')
      .replace('background: #B04D2E;', 'background: #0284C7;')
      .replace('background: white;', 'background: #334155;')
      .replace('color: #5C4A3A;', 'color: #E2E8F0;')
      .replace('background: #EDE4D8;', 'background: #475569;')
      .replace('background: #D9CDBE;', 'background: #64748B;')
      .replace('border-top: 1px solid #EDE4D8;', 'border-top: 1px solid #475569;')
  }
  return html
}

function isNpmAvailable(): boolean {
  try {
    execSync('npm --version', { stdio: 'ignore', timeout: 5000 })
    return true
  } catch { return false }
}

function findAvailablePort(basePort: number): number {
  const { execSync } = require('child_process') as typeof import('child_process')
  for (let offset = 0; offset < 100; offset++) {
    const port = basePort + offset
    try {
      // Run a synchronous child process to verify if the port is open.
      // Must set ELECTRON_RUN_AS_NODE to execute as pure Node CLI in Electron env.
      execSync(
        `"${process.execPath}" -e "const s = require('net').createServer(); s.once('error', () => process.exit(1)); s.once('listening', () => { s.close(); process.exit(0); }); s.listen(${port}, '127.0.0.1');"`,
        { stdio: 'ignore', timeout: 2000, env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' } }
      )
      return port
    } catch {
      // Port is busy or check failed, try next offset
    }
  }
  return basePort + Math.floor(Math.random() * 1000)
}

function buildStaticServerScript(sandboxPath: string, port: number): string {
  return `
const http = require('http');
const fs = require('fs');
const path = require('path');
const sandboxRoot = ${JSON.stringify(sandboxPath)};
function getCT(fp) {
  const t={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon','.txt':'text/plain'};
  return t[path.extname(fp).toLowerCase()]||'text/plain';
}
const srv = http.createServer((req,res)=>{
  try {
    let fp = path.join(sandboxRoot, req.url==='/'?'index.html':req.url.split('?')[0]);
    if(!fp.startsWith(sandboxRoot)) {res.writeHead(403);res.end('Forbidden');return;}
    if(fs.existsSync(fp)&&fs.statSync(fp).isFile()) {
      res.writeHead(200,{'Content-Type':getCT(fp),'Access-Control-Allow-Origin':'*'});
      res.end(fs.readFileSync(fp));
    } else {
      const idx=path.join(sandboxRoot,'index.html');
      if(fs.existsSync(idx)) {res.writeHead(200,{'Content-Type':'text/html'});res.end(fs.readFileSync(idx));}
      else {res.writeHead(404);res.end('Not found');}
    }
  } catch(e){res.writeHead(500);res.end('Server error');}
});
srv.listen(${port},'127.0.0.1',()=>{console.log('AUREON_PREVIEW_READY:'+${port});});
srv.on('error',(e)=>{console.error('AUREON_PREVIEW_ERROR:'+e.message);process.exit(1);});
`
}

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain'
}

// ── Service ─────────────────────────────────────────────────────

export const livePreviewService = {
  _session: null as PreviewSession | null,
  _httpServer: null as http.Server | null,
  _statusChangeCallback: null as ((status: PreviewStatus) => void) | null,

  /**
   * Register a callback that fires whenever the preview status transitions
   * to 'running' or 'error'. Used by the IPC layer to push events to the renderer.
   * Returns a function to unsubscribe.
   */
  onStatusChange(cb: (status: PreviewStatus) => void): () => void {
    this._statusChangeCallback = cb
    return () => { this._statusChangeCallback = null }
  },

  _emitStatusChange(): void {
    if (this._statusChangeCallback) {
      try { this._statusChangeCallback(this._status()) } catch { /* nop */ }
    }
  },

  getSandboxRoot(): string {
    const sandboxDir = path.join(app.getPath('userData'), 'preview-sandbox')
    if (!fs.existsSync(sandboxDir)) fs.mkdirSync(sandboxDir, { recursive: true })
    return sandboxDir
  },

  createSandbox(input: CreateSandboxInput = {}): { success: boolean; sandboxPath: string; error?: string } {
    try {
      const templateType = input.templateType || 'html'
      const sessionId = uuid()
      const sandboxRoot = this.getSandboxRoot()
      const sandboxPath = path.join(sandboxRoot, sessionId)

      if (fs.existsSync(sandboxPath)) fs.rmSync(sandboxPath, { recursive: true, force: true })
      fs.mkdirSync(sandboxPath, { recursive: true })

      if (templateType === 'html') {
        fs.writeFileSync(path.join(sandboxPath, 'index.html'), SAMPLE_HTML, 'utf-8')
      } else if (templateType === 'demo') {
        const selectedStyle = input.style || 'Calming Ivory'
        const htmlContent = applyStyleToHtml(DEMO_COUNTER_HTML, selectedStyle)
        fs.writeFileSync(path.join(sandboxPath, 'index.html'), htmlContent, 'utf-8')
        // Marker file so startPreview detects the demo template type
        fs.writeFileSync(path.join(sandboxPath, '.vibeforge-demo'), templateType, 'utf-8')
        fs.writeFileSync(path.join(sandboxPath, '.aureon-demo'), templateType, 'utf-8')
      } else if (templateType === 'vite-react') {
        const srcDir = path.join(sandboxPath, 'src')
        fs.mkdirSync(srcDir, { recursive: true })
        fs.writeFileSync(path.join(sandboxPath, 'index.html'),
          '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Vibeforge Preview</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>',
          'utf-8')
        fs.writeFileSync(path.join(sandboxPath, 'package.json'), JSON.stringify({
          name: 'vibeforge-preview', private: true, version: '1.0.0', type: 'module',
          scripts: { dev: 'vite --host 127.0.0.1', build: 'vite build', preview: 'vite preview' },
          dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0' },
          devDependencies: { '@vitejs/plugin-react': '^4.4.0', 'vite': '^6.1.0' }
        }, null, 2), 'utf-8')
        fs.writeFileSync(path.join(sandboxPath, 'vite.config.ts'),
          'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\nexport default defineConfig({ plugins: [react()] });', 'utf-8')
        fs.writeFileSync(path.join(srcDir, 'main.tsx'),
          'import React,{useState}from"react";import ReactDOM from"react-dom/client";function App(){const[c,set]=useState(0);return(<div style={{textAlign:"center",padding:"3rem",fontFamily:"system-ui",background:"#FAF8F5",minHeight:"100vh"}}><div style={{background:"white",borderRadius:12,padding:"2rem",maxWidth:420,margin:"0 auto",boxShadow:"0 4px 24px rgba(44,36,22,0.08)"}}><h1 style={{fontFamily:"Georgia,serif",fontSize:"1.5rem",color:"#C75B39",marginBottom:"0.5rem"}}>Aureon Preview</h1><p style={{color:"#6B5E4A",marginBottom:"1rem"}}>React sandbox</p><div style={{fontSize:"2rem",fontWeight:"bold",margin:"1rem 0"}}>{c}</div><button onClick={()=>set(c+1)}style={{background:"#C75B39",color:"white",border:"none",padding:"0.5rem 1.5rem",borderRadius:8,cursor:"pointer",fontSize:"0.875rem"}}>Click Me</button></div></div>)}ReactDOM.createRoot(document.getElementById("root")!).render(<App/>);',
          'utf-8')
      }

      logger.info(`Sandbox created: ${sandboxPath} (template: ${templateType})`)
      return { success: true, sandboxPath }
    } catch (err) {
      const msg = String(err)
      logger.error(`Failed to create sandbox: ${msg}`)
      return { success: false, sandboxPath: '', error: msg }
    }
  },

  /**
   * Safe Generated Preview Flow: sets up the sandbox path, writes files (redacting secrets,
   * blocking path traversal), and launches the HTTP preview server.
   */
  startGeneratedPreview(input: StartGeneratedPreviewInput): PreviewStatus {
    const templateType = input.source === 'code-demo' ? 'demo' : 'html'
    const sessionId = uuid()
    const sandboxRoot = this.getSandboxRoot()
    const sandboxPath = path.join(sandboxRoot, sessionId)

    try {
      if (fs.existsSync(sandboxPath)) fs.rmSync(sandboxPath, { recursive: true, force: true })
      fs.mkdirSync(sandboxPath, { recursive: true })

      const entry = input.entryFile || 'index.html'

      if (input.files && Object.keys(input.files).length > 0) {
        for (const [relPath, content] of Object.entries(input.files)) {
          // Block path traversal
          const resolved = path.resolve(sandboxPath, relPath)
          if (!resolved.startsWith(path.resolve(sandboxPath))) {
            throw new Error('Path escapes sandbox directory')
          }
          const dir = path.dirname(resolved)
          if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })

          // Redact secrets
          const redactedContent = redactSecrets(content)
          fs.writeFileSync(resolved, redactedContent, 'utf-8')
        }
      } else {
        // Write standard demo counter
        const selectedStyle = input.style || 'Calming Ivory'
        const htmlContent = applyStyleToHtml(DEMO_COUNTER_HTML, selectedStyle)
        fs.writeFileSync(path.join(sandboxPath, entry), htmlContent, 'utf-8')
        // Marker file so startPreview detects the demo template type
        fs.writeFileSync(path.join(sandboxPath, '.vibeforge-demo'), 'demo', 'utf-8')
        fs.writeFileSync(path.join(sandboxPath, '.aureon-demo'), 'demo', 'utf-8')
      }

      logger.info(`startGeneratedPreview: sandbox created at ${sandboxPath} (source: ${input.source})`)

      // Start static preview server
      return this.startPreview(sandboxPath, input.port)
    } catch (err: any) {
      logger.error(`startGeneratedPreview failed: ${err.message}`)
      const logs = [{ timestamp: new Date().toISOString(), stream: 'stderr' as const, text: err.message }]
      this._session = {
        id: sessionId,
        sandboxPath,
        sandboxUrl: '',
        status: 'error',
        port: input.port || 0,
        process: null,
        logs,
        templateType,
        createdAt: new Date().toISOString(),
        error: err.message
      }
      return this._status()
    }
  },

  /**
   * Self-Test Coding Agent Demo: generates the Vibeforge Counter Demo sandbox,
   * starts the preview server, and returns the full result.
   */
  createDemo(port?: number, style?: string): CodingDemoResult {
    try {
      const status = this.startGeneratedPreview({
        source: 'code-demo',
        style,
        port
      })
      const sandboxPath = status.sandboxPath!
      const sandboxId = path.basename(sandboxPath)
      return {
        success: status.status !== 'error',
        sandboxId,
        sandboxPath,
        url: status.url,
        filesWritten: [path.join(sandboxPath, 'index.html')],
        previewStatus: status,
        error: status.error || undefined,
      }
    } catch (err) {
      const msg = String(err)
      logger.error(`Coding Demo failed: ${msg}`)
      return { success: false, sandboxId: '', sandboxPath: '', url: null, filesWritten: [], previewStatus: this.getStatus(), error: msg }
    }
  },

  startPreview(sandboxPath: string, port = 0): PreviewStatus {
    const existing = this._session
    if (existing && (existing.status === 'running' || existing.status === 'starting')) {
      this.stopPreview()
    }

    const sessionId = uuid()
    const actualPort = port || findAvailablePort(3100)

    if (!fs.existsSync(sandboxPath)) {
      return { id: null, status: 'error', sandboxPath, url: null, port: null, templateType: null, logs: [], error: `Sandbox path not found: ${sandboxPath}` }
    }

    const isDemo = fs.existsSync(path.join(sandboxPath, '.vibeforge-demo')) || fs.existsSync(path.join(sandboxPath, '.aureon-demo'))
    const hasPackageJson = fs.existsSync(path.join(sandboxPath, 'package.json'))
    const templateType = isDemo ? 'demo' : hasPackageJson ? 'vite-react' : 'html'

    const logs: PreviewLogEntry[] = []
    const addLog = (stream: 'stdout' | 'stderr', text: string) => {
      logs.push({ timestamp: new Date().toISOString(), stream, text: redactSecrets(text) })
    }

    const session: PreviewSession = {
      id: sessionId, sandboxPath, sandboxUrl: `http://127.0.0.1:${actualPort}`,
      status: 'starting', port: actualPort, process: null,
      logs, templateType, createdAt: new Date().toISOString(), error: null,
    }
    this._session = session

    try {
      if (hasPackageJson) {
        if (!isNpmAvailable()) {
          session.status = 'error'
          session.error = 'npm is not available. Use the Simple HTML or Demo template instead.'
          addLog('stderr', session.error!)
          return this._status()
        }
        addLog('stdout', 'Running npm install...')
        try {
          execSync('npm install', { cwd: sandboxPath, stdio: 'pipe', timeout: 120000, env: { ...process.env, NODE_ENV: 'development' }, shell: true as any })
          addLog('stdout', 'Dependencies installed.')
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e)
          addLog('stderr', `npm install failed: ${msg}`)
          session.status = 'error'; session.error = `Failed to install: ${msg}`
          return this._status()
        }
        addLog('stdout', `Starting Vite on port ${actualPort}...`)
        const proc = spawn('npx', ['vite', '--host', '127.0.0.1', '--port', String(actualPort)], {
          cwd: sandboxPath, env: { ...process.env, NODE_ENV: 'development' }, stdio: ['ignore', 'pipe', 'pipe'], shell: true
        })

        session.process = proc
        let readyTimer: ReturnType<typeof setTimeout> | null = null
        let lastStderr = ''

        proc.stdout?.on('data', (data: Buffer) => {
          const text = data.toString()
          addLog('stdout', text)
          if (text.includes('Local:') && text.includes('http') && session.status === 'starting') {
            session.status = 'running'
            if (readyTimer) clearTimeout(readyTimer)
          }
        })
        proc.stderr?.on('data', (data: Buffer) => {
          const text = data.toString()
          addLog('stderr', text)
          lastStderr = (lastStderr + text).slice(-500)
        })
        proc.on('error', (err) => {
          addLog('stderr', `Process error: ${err.message}`)
          session.status = 'error'; session.error = err.message
          if (readyTimer) clearTimeout(readyTimer)
        })
        proc.on('close', (code) => {
          if (readyTimer) clearTimeout(readyTimer)
          addLog('stdout', `Server exited code ${code}`)
          if (session.status === 'starting' || session.status === 'running') {
            if (code !== 0) {
              session.status = 'error'
              const cleanStderr = lastStderr.trim()
              session.error = cleanStderr
                ? `Server exited code ${code}: ${cleanStderr}`
                : `Server exited code ${code}`
            } else {
              session.status = 'stopped'
            }
          }
        })

        readyTimer = setTimeout(() => {
          if (session.status === 'starting') {
            session.status = 'error'; session.error = 'Server failed to start within 60s'
            addLog('stderr', session.error!)
            try { proc.kill('SIGTERM') } catch { /* nop */ }
          }
        }, 60000)

      } else {
        // Start in-process HTTP static server
        addLog('stdout', `Starting in-process static server on port ${actualPort}...`)

        const server = http.createServer((req, res) => {
          try {
            const decoded = decodeURIComponent(req.url || '/')
            const cleanPath = decoded.split('?')[0]

            const filePath = path.join(sandboxPath, cleanPath === '/' ? 'index.html' : cleanPath)

            // Safety check: ensure resolved filePath starts with resolved sandboxPath
            const resolvedSandbox = path.resolve(sandboxPath)
            const resolvedFile = path.resolve(filePath)
            if (!resolvedFile.startsWith(resolvedSandbox)) {
              res.writeHead(403, { 'Content-Type': 'text/plain', 'Access-Control-Allow-Origin': '*' })
              res.end('Forbidden')
              return
            }

            if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
              const ext = path.extname(filePath).toLowerCase()
              const contentType = MIME_TYPES[ext] || 'text/plain'
              res.writeHead(200, {
                'Content-Type': contentType,
                'Access-Control-Allow-Origin': '*'
              })
              res.end(fs.readFileSync(filePath))
            } else {
              // Only fall back to index.html for extensionless routes (SPA routing).
              // For missing asset files (.js, .css, .svg, .png, etc.), return 404
              // so the browser doesn't try to render HTML as a script/stylesheet.
              const ext = path.extname(cleanPath).toLowerCase()
              if (!ext) {
                const indexHtml = path.join(sandboxPath, 'index.html')
                if (fs.existsSync(indexHtml)) {
                  res.writeHead(200, { 'Content-Type': 'text/html', 'Access-Control-Allow-Origin': '*' })
                  res.end(fs.readFileSync(indexHtml))
                  return
                }
              }
              res.writeHead(404, { 'Content-Type': 'text/plain', 'Access-Control-Allow-Origin': '*' })
              res.end('Not Found')
            }
          } catch (e: any) {
            res.writeHead(500, { 'Content-Type': 'text/plain', 'Access-Control-Allow-Origin': '*' })
            res.end(`Server Error: ${e.message}`)
          }
        })

        server.listen(actualPort, '127.0.0.1', () => {
          addLog('stdout', `Static server listening on http://127.0.0.1:${actualPort}`)
          if (this._session && this._session.id === sessionId) {
            this._session.status = 'running'
            // Push status change to renderer immediately (no poll delay)
            this._emitStatusChange()
          }
        })

        server.on('error', (err: any) => {
          addLog('stderr', `Server error: ${err.message}`)
          if (this._session && this._session.id === sessionId) {
            this._session.status = 'error'
            this._session.error = err.message
            // Push error status to renderer immediately
            this._emitStatusChange()
          }
        })

        this._httpServer = server
      }

      return this._status()
    } catch (err) {
      const msg = String(err)
      addLog('stderr', msg); session.status = 'error'; session.error = msg
      return this._status()
    }
  },

  stopPreview(): PreviewStatus {
    const s = this._session

    if (this._httpServer) {
      try {
        this._httpServer.close()
      } catch (err) {
        logger.error(`Error closing in-process http server: ${err}`)
      }
      this._httpServer = null
    }

    if (s?.process) {
      try {
        s.process.kill('SIGTERM')
        setTimeout(() => {
          try { s.process?.kill('SIGKILL') } catch { /* nop */ }
        }, 2000)
      } catch {
        /* dead */
      }
      s.process = null
    }

    if (s) {
      s.status = 'stopped'
    }
    return this._status()
  },

  getStatus(): PreviewStatus { return this._status() },

  _status(): PreviewStatus {
    const s = this._session
    if (!s) return { id: null, status: 'idle', sandboxPath: null, url: null, port: null, templateType: null, logs: [], error: null }
    return { id: s.id, status: s.status, sandboxPath: s.sandboxPath, url: s.sandboxUrl, port: s.port, templateType: s.templateType, logs: s.logs.slice(-100), error: s.error }
  },

  writeSandboxFile(sandboxPath: string, relativePath: string, content: string): { success: boolean; error?: string } {
    try {
      const resolved = path.resolve(sandboxPath, relativePath)
      if (!resolved.startsWith(path.resolve(sandboxPath))) return { success: false, error: 'Path escapes sandbox directory' }
      const dir = path.dirname(resolved)
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(resolved, content, 'utf-8')
      return { success: true }
    } catch (err) { return { success: false, error: String(err) } }
  },

  listSandboxes(): Array<{ id: string; path: string; createdAt: string }> {
    try {
      const root = this.getSandboxRoot()
      if (!fs.existsSync(root)) return []
      return fs.readdirSync(root).filter(n => fs.statSync(path.join(root, n)).isDirectory()).map(n => {
        const full = path.join(root, n); const s = fs.statSync(full)
        return { id: n, path: full, createdAt: s.birthtime.toISOString() }
      }).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    } catch { return [] }
  },

  cleanupSandboxes(maxAgeHours = 24): number {
    try {
      const root = this.getSandboxRoot()
      if (!fs.existsSync(root)) return 0
      const cutoff = Date.now() - maxAgeHours * 60 * 60 * 1000; let cleaned = 0
      for (const n of fs.readdirSync(root)) {
        const full = path.join(root, n)
        try { if (fs.statSync(full).isDirectory() && fs.statSync(full).birthtimeMs < cutoff) { fs.rmSync(full, { recursive: true, force: true }); cleaned++ } } catch { /* skip */ }
      }
      return cleaned
    } catch { return 0 }
  },

  reset(): void { this._session = null; this._statusChangeCallback = null },
}

try { if (typeof app.on === 'function') app.on('before-quit', () => livePreviewService.stopPreview()) } catch { /* test env */ }
