import type { SkillDefinition, PermissionType } from '../../shared/types/routing'

/**
 * SkillRegistry — built-in skill definitions.
 * Skills represent capabilities that agents or users can leverage.
 * Local/imported skills are discovered from the filesystem at runtime.
 */

export const BUILTIN_SKILLS: SkillDefinition[] = [
  {
    id: 'code-generation',
    name: 'Code Generation',
    description: 'Generate production-quality code with proper error handling, types, and comments.',
    tags: ['coding', 'typescript', 'react', 'nodejs', 'python'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.ts', '*.tsx', '*.js', '*.jsx', '*.py', '*.rs', '*.go'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'code-analysis',
    name: 'Code Analysis',
    description: 'Analyze existing code for patterns, issues, complexity, and improvement opportunities.',
    tags: ['coding', 'analysis', 'quality'],
    requiredPermissions: ['file_read'],
    allowedFilePatterns: ['*'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'debugging',
    name: 'Debugging',
    description: 'Systematic debugging: reproduce issues, read stack traces, isolate root causes.',
    tags: ['debugging', 'troubleshooting'],
    requiredPermissions: ['file_read', 'terminal_read'],
    allowedFilePatterns: ['*'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'refactoring',
    name: 'Refactoring',
    description: 'Restructure code to improve readability and maintainability without changing behavior.',
    tags: ['coding', 'quality'],
    requiredPermissions: ['file_read', 'file_write'],
    allowedFilePatterns: ['*.ts', '*.tsx', '*.js', '*.jsx', '*.py', '*.rs', '*.go'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'testing',
    name: 'Testing',
    description: 'Write and maintain comprehensive tests: unit, integration, e2e, and edge cases.',
    tags: ['testing', 'quality', 'vitest', 'jest'],
    requiredPermissions: ['file_read', 'file_write'],
    allowedFilePatterns: ['*.test.*', '*.spec.*', '__tests__/**'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'architecture',
    name: 'Software Architecture',
    description: 'Design system architecture, component relationships, data flow, and tech decisions.',
    tags: ['architecture', 'design', 'planning'],
    requiredPermissions: [],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'security',
    name: 'Security Audit',
    description: 'Review code and configurations for security vulnerabilities and best practices.',
    tags: ['security', 'audit', 'vulnerability'],
    requiredPermissions: ['file_read'],
    allowedFilePatterns: ['*'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'git',
    name: 'Git Operations',
    description: 'Manage git workflows: commits, branches, merges, rebases, and pull requests.',
    tags: ['git', 'github', 'version-control'],
    requiredPermissions: ['git_read', 'git_write'],
    allowedFilePatterns: ['.git/**'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis',
    description: 'Analyze datasets, write SQL queries, generate insights, and create visualizations.',
    tags: ['data', 'analysis', 'sql', 'visualization'],
    requiredPermissions: ['file_read', 'db_read'],
    allowedFilePatterns: ['*.csv', '*.json', '*.sql', '*.db', '*.sqlite'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'sql',
    name: 'SQL Query Writing',
    description: 'Write efficient SQL queries, design schemas, and optimize database performance.',
    tags: ['sql', 'database', 'schema'],
    requiredPermissions: ['db_read', 'db_write'],
    allowedFilePatterns: ['*.sql'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'design',
    name: 'UI/UX Design',
    description: 'Design interfaces, component libraries, layouts, and visual styling.',
    tags: ['design', 'css', 'ui', 'ux', 'accessibility'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.css', '*.scss', '*.less', '*.tsx', '*.jsx'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'css',
    name: 'CSS & Styling',
    description: 'Implement and refactor CSS, Tailwind, design tokens, and responsive layouts.',
    tags: ['css', 'tailwind', 'styling', 'responsive'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.css', '*.scss', '*.less', '*.tsx', '*.jsx'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'writing',
    name: 'Technical Writing',
    description: 'Write clear, structured documentation, guides, READMEs, and API references.',
    tags: ['writing', 'documentation', 'markdown'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.md', '*.mdx', '*.txt', '*.rst'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'markdown',
    name: 'Markdown Authoring',
    description: 'Author and format Markdown documents with proper structure, tables, and code blocks.',
    tags: ['markdown', 'documentation', 'formatting'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.md', '*.mdx'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    description: 'Craft effective system prompts, templates, and AI interaction patterns.',
    tags: ['prompt', 'ai', 'template'],
    requiredPermissions: [],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'research',
    name: 'Web Research',
    description: 'Research topics online, synthesize findings from multiple sources.',
    tags: ['research', 'web', 'synthesis'],
    requiredPermissions: ['network_outbound'],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'communication',
    name: 'General Communication',
    description: 'Clear, concise, and helpful communication for general conversations.',
    tags: ['communication', 'general'],
    requiredPermissions: [],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'explanation',
    name: 'Technical Explanation',
    description: 'Explain complex technical concepts in clear, accessible language.',
    tags: ['explanation', 'teaching', 'communication'],
    requiredPermissions: [],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'logging',
    name: 'Logging & Diagnostics',
    description: 'Set up and interpret logging, monitoring, and diagnostic systems.',
    tags: ['logging', 'monitoring', 'diagnostics', 'debugging'],
    requiredPermissions: ['file_read', 'terminal_read'],
    allowedFilePatterns: ['*.log', '*.json'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'version-control',
    name: 'Version Control',
    description: 'Best practices for version control workflows and repository management.',
    tags: ['git', 'version-control', 'github'],
    requiredPermissions: ['git_read'],
    allowedFilePatterns: ['.git/**'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'visualization',
    name: 'Data Visualization',
    description: 'Create charts, graphs, and interactive visualizations from data.',
    tags: ['visualization', 'charts', 'data'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.tsx', '*.jsx', '*.html'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'accessibility',
    name: 'Accessibility (a11y)',
    description: 'Ensure web interfaces meet WCAG standards and are accessible to all users.',
    tags: ['accessibility', 'a11y', 'design', 'ui'],
    requiredPermissions: ['file_read'],
    allowedFilePatterns: ['*.tsx', '*.jsx', '*.html', '*.css'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'typescript',
    name: 'TypeScript Expert',
    description: 'Advanced TypeScript patterns, generics, type safety, and best practices.',
    tags: ['typescript', 'types', 'coding'],
    requiredPermissions: ['file_read', 'file_write'],
    allowedFilePatterns: ['*.ts', '*.tsx'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'react',
    name: 'React Specialist',
    description: 'React patterns, hooks, state management, performance, and best practices.',
    tags: ['react', 'frontend', 'ui', 'coding'],
    requiredPermissions: ['file_read', 'file_write'],
    allowedFilePatterns: ['*.tsx', '*.jsx'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'nodejs',
    name: 'Node.js Backend',
    description: 'Node.js APIs, middleware, database integration, and server architecture.',
    tags: ['nodejs', 'backend', 'api', 'server'],
    requiredPermissions: ['file_read', 'file_write', 'terminal_write'],
    allowedFilePatterns: ['*.ts', '*.js', '*.json'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'auditing',
    name: 'Compliance Auditing',
    description: 'Audit systems and configurations for compliance with standards and regulations.',
    tags: ['audit', 'compliance', 'security'],
    requiredPermissions: ['file_read'],
    allowedFilePatterns: ['*'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'code-quality',
    name: 'Code Quality',
    description: 'Assess and improve code quality: linting, formatting, complexity analysis.',
    tags: ['quality', 'linting', 'formatting', 'analysis'],
    requiredPermissions: ['file_read'],
    allowedFilePatterns: ['*'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'synthesis',
    name: 'Information Synthesis',
    description: 'Combine information from multiple sources into coherent, structured output.',
    tags: ['synthesis', 'research', 'writing'],
    requiredPermissions: [],
    allowedFilePatterns: [],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
  {
    id: 'ui-ux',
    name: 'UI/UX Design',
    description: 'User interface and user experience design patterns and best practices.',
    tags: ['ui', 'ux', 'design'],
    requiredPermissions: ['file_write'],
    allowedFilePatterns: ['*.tsx', '*.jsx', '*.html', '*.css'],
    version: '1.0.0',
    source: 'builtin',
    isEnabled: true,
  },
]

/** Get all enabled built-in skills */
export function getBuiltinSkills(): SkillDefinition[] {
  return BUILTIN_SKILLS.filter(s => s.isEnabled)
}

/** Find skills matching required IDs */
export function findSkillsByIds(ids: string[]): SkillDefinition[] {
  return BUILTIN_SKILLS.filter(s => ids.includes(s.id))
}

/** Find skills matching given tags */
export function findSkillsByTags(tags: string[]): SkillDefinition[] {
  const lower = tags.map(t => t.toLowerCase())
  return BUILTIN_SKILLS.filter(s =>
    s.tags.some(t => lower.includes(t.toLowerCase()))
  )
}

/** Get skills matching permissions user has granted */
export function findSkillsByPermissions(allowedPermissions: PermissionType[]): SkillDefinition[] {
  return BUILTIN_SKILLS.filter(s =>
    s.requiredPermissions.every(p => allowedPermissions.includes(p))
  )
}

/** Merge built-in skills with imported/local skills (from filesystem discovery) */
export function getAllSkills(importedSkills: SkillDefinition[] = []): SkillDefinition[] {
  return [...BUILTIN_SKILLS, ...importedSkills]
}
