/**
 * Aureon Desk — Skill Education Center
 *
 * Beginner-friendly explanations for Aureon skills.
 * Each skill has a simple description, inputs, outputs, permissions, and examples.
 */

export interface SkillEducation {
  id: string
  name: string
  icon: string // Lucide icon name
  simpleDescription: string
  inputFields: string[]
  outputArtifactType: string
  requiredPermissions: string[]
  examples: string[]
  relatedTemplates: string[]
  testStatus: 'tested' | 'partial' | 'not-tested'
  category: 'coding' | 'preview' | 'design' | 'providers' | 'social' | 'cleanup' | 'docs' | 'general'
}

export const SKILL_EDUCATION: SkillEducation[] = [
  {
    id: 'create-landing-page',
    name: 'Create Landing Page',
    icon: 'Layout',
    simpleDescription: 'Builds a beautiful, responsive landing page with hero section, features, and call-to-action buttons. Uses the Aureon calm ivory theme by default.',
    inputFields: ['Page topic', 'Target audience', 'Sections needed', 'Color preferences'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Create a landing page for a developer tool', 'Build a product launch page with testimonials'],
    relatedTemplates: ['build-web-app', 'improve-ui-theme'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'create-android-style-prototype',
    name: 'Create Android Prototype',
    icon: 'Smartphone',
    simpleDescription: 'Generates an Android-style UI prototype with Material Design components. Creates interactive mockups that look like real Android apps.',
    inputFields: ['App type', 'Screen descriptions', 'Color scheme', 'Navigation style'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Create a music player app prototype', 'Build a fitness tracker UI with bottom navigation'],
    relatedTemplates: ['build-android-app', 'create-landing-page'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'create-counter-app',
    name: 'Create Counter App',
    icon: 'PlusCircle',
    simpleDescription: 'Generates a simple counter application with increment, decrement, and reset functionality. Great for learning and testing the build pipeline.',
    inputFields: ['Title', 'Starting value', 'Step amount'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Create a pomodoro-style counter', 'Build a score tracker for a game'],
    relatedTemplates: ['create-todo-app', 'build-web-app'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'create-todo-app',
    name: 'Create Todo App',
    icon: 'CheckSquare',
    simpleDescription: 'Generates a full-featured todo application with add, complete, delete, and filter operations. Includes local storage for persistence.',
    inputFields: ['App name', 'Features needed', 'Design style'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Create a shopping list app', 'Build a project task tracker with due dates'],
    relatedTemplates: ['create-counter-app', 'build-web-app'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'generate-file-operations',
    name: 'Generate File Operations',
    icon: 'FileCode',
    simpleDescription: 'Creates, updates, deletes, renames, and organizes files in your project. Shows a diff preview before applying any changes.',
    inputFields: ['File paths', 'Operation type', 'New content'],
    outputArtifactType: 'diff',
    requiredPermissions: ['file_read', 'file_write'],
    examples: ['Rename all component files to PascalCase', 'Move utility functions into a shared folder'],
    relatedTemplates: ['show-diff', 'clean-dead-code'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'show-diff',
    name: 'Show Diff',
    icon: 'GitCompare',
    simpleDescription: 'Shows a visual side-by-side comparison of file changes. Green for added lines, red for removed lines. Helps you review changes before applying them.',
    inputFields: ['Original file', 'Modified file'],
    outputArtifactType: 'diff',
    requiredPermissions: ['file_read'],
    examples: ['Show what changed in my latest refactor', 'Compare two versions of a component'],
    relatedTemplates: ['generate-file-operations'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'start-live-preview',
    name: 'Start Live Preview',
    icon: 'Play',
    simpleDescription: 'Starts a local server and opens a live preview of your app. Shows your changes in real-time as you build.',
    inputFields: ['Entry file', 'Port number'],
    outputArtifactType: 'preview',
    requiredPermissions: ['file_read', 'terminal_write'],
    examples: ['Preview my React app at localhost:3000', 'Start a demo preview of the landing page'],
    relatedTemplates: ['test-live-preview', 'create-landing-page'],
    testStatus: 'tested',
    category: 'preview',
  },
  {
    id: 'test-live-preview',
    name: 'Test Live Preview',
    icon: 'MonitorCheck',
    simpleDescription: 'Tests that your live preview is working correctly. Checks for errors, verifies the page loads, and confirms all elements render.',
    inputFields: ['URL to test', 'Expected elements'],
    outputArtifactType: 'error-diagnostic',
    requiredPermissions: ['network_outbound'],
    examples: ['Verify my app loads without errors', 'Check that all navigation links work'],
    relatedTemplates: ['start-live-preview'],
    testStatus: 'partial',
    category: 'preview',
  },
  {
    id: 'improve-ui-theme',
    name: 'Improve UI Theme',
    icon: 'Palette',
    simpleDescription: 'Enhances your app with the Aureon calm ivory design system. Applies consistent colors, typography, spacing, and rounded corners.',
    inputFields: ['Current theme', 'Desired style', 'Color preferences'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Apply the Aureon ivory theme to my app', 'Create a dark mode version of my design'],
    relatedTemplates: ['generate-brand-assets', 'create-landing-page'],
    testStatus: 'tested',
    category: 'design',
  },
  {
    id: 'generate-brand-assets',
    name: 'Generate Brand Assets',
    icon: 'Image',
    simpleDescription: 'Creates brand assets — logos, icons, banners, and color palettes. Generates SVG source files and PNG/ICO outputs for different platforms.',
    inputFields: ['Brand name', 'Color preferences', 'Asset types needed'],
    outputArtifactType: 'code',
    requiredPermissions: ['file_write'],
    examples: ['Generate app icons in all required sizes', 'Create a GitHub social preview banner'],
    relatedTemplates: ['improve-ui-theme'],
    testStatus: 'tested',
    category: 'design',
  },
  {
    id: 'import-skills',
    name: 'Import Skills',
    icon: 'Download',
    simpleDescription: 'Imports skill metadata from external catalogs like VoltAgent/awesome-agent-skills. Never copies source code — only imports names, URLs, and descriptions.',
    inputFields: ['Source URL', 'Local file path'],
    outputArtifactType: 'text',
    requiredPermissions: ['network_outbound', 'file_read'],
    examples: ['Import skills from the VoltAgent catalog', 'Load a local skill metadata file'],
    relatedTemplates: [],
    testStatus: 'tested',
    category: 'general',
  },
  {
    id: 'explain-error',
    name: 'Explain Error',
    icon: 'AlertCircle',
    simpleDescription: 'Takes an error message and explains it in plain English. Shows the root cause and suggests specific fixes with code examples.',
    inputFields: ['Error message', 'Stack trace', 'What you were trying to do'],
    outputArtifactType: 'error-diagnostic',
    requiredPermissions: ['file_read'],
    examples: ["Explain this 'Module not found' error", 'Why am I getting a CORS error in my API?'],
    relatedTemplates: ['test-provider'],
    testStatus: 'tested',
    category: 'coding',
  },
  {
    id: 'test-provider',
    name: 'Test Provider',
    icon: 'Zap',
    simpleDescription: 'Tests your AI provider connection. Verifies API keys work, checks model availability, and diagnoses common setup issues.',
    inputFields: ['Provider name', 'API key', 'Model to test'],
    outputArtifactType: 'error-diagnostic',
    requiredPermissions: ['network_outbound'],
    examples: ['Test my OpenRouter API key', 'Check if Ollama is running locally'],
    relatedTemplates: ['explain-error'],
    testStatus: 'tested',
    category: 'providers',
  },
  {
    id: 'setup-mcp-server',
    name: 'Setup MCP Server',
    icon: 'Server',
    simpleDescription: 'Helps you set up a Model Context Protocol (MCP) server to connect external tools. Guides you through configuration, testing, and security.',
    inputFields: ['Server type', 'Connection details', 'Tools to expose'],
    outputArtifactType: 'provider-setup',
    requiredPermissions: ['file_read', 'file_write', 'network_outbound'],
    examples: ['Set up a Filesystem MCP server', 'Connect a database MCP tool for SQL queries'],
    relatedTemplates: ['import-skills'],
    testStatus: 'partial',
    category: 'providers',
  },
  {
    id: 'draft-social-post',
    name: 'Draft Social Post',
    icon: 'MessageCircle',
    simpleDescription: 'Creates draft social media posts for different platforms. Generates engaging content with hashtags, mentions, and platform-optimized formatting.',
    inputFields: ['Topic', 'Platform', 'Tone', 'Key points'],
    outputArtifactType: 'text',
    requiredPermissions: [],
    examples: ['Write a LinkedIn post about our new feature', 'Create a Twitter thread explaining a technical concept'],
    relatedTemplates: ['create-youtube-description'],
    testStatus: 'tested',
    category: 'social',
  },
  {
    id: 'create-youtube-description',
    name: 'Create YouTube Description',
    icon: 'Video',
    simpleDescription: 'Writes YouTube video descriptions with timestamps, links, and SEO-optimized text. Includes chapter markers and call-to-action sections.',
    inputFields: ['Video title', 'Content summary', 'Links to include', 'Chapters'],
    outputArtifactType: 'text',
    requiredPermissions: [],
    examples: ['Write a description for my coding tutorial', 'Create timestamps for a 30-minute walkthrough'],
    relatedTemplates: ['draft-social-post'],
    testStatus: 'tested',
    category: 'social',
  },
  {
    id: 'create-tutorial',
    name: 'Create Tutorial',
    icon: 'BookOpen',
    simpleDescription: 'Generates step-by-step tutorials with code examples, explanations, and screenshots. Perfect for teaching concepts to beginners.',
    inputFields: ['Topic', 'Skill level', 'Format', 'Code language'],
    outputArtifactType: 'markdown',
    requiredPermissions: ['file_write'],
    examples: ['Create a React hooks tutorial for beginners', 'Write a guide for setting up an Electron app'],
    relatedTemplates: ['create-landing-page', 'create-counter-app'],
    testStatus: 'tested',
    category: 'docs',
  },
  {
    id: 'clean-dead-code',
    name: 'Clean Dead Code',
    icon: 'Trash2',
    simpleDescription: 'Scans your project for unused files, dead exports, and unreachable code. Safely removes what is not used while keeping everything that is.',
    inputFields: ['Project path', 'Files to check'],
    outputArtifactType: 'file-tree',
    requiredPermissions: ['file_read', 'file_write'],
    examples: ['Find and remove unused components', 'Clean up dead imports across the project'],
    relatedTemplates: ['generate-file-operations', 'show-diff'],
    testStatus: 'tested',
    category: 'cleanup',
  },
  {
    id: 'build-beta-release',
    name: 'Build Beta Release',
    icon: 'Package',
    simpleDescription: 'Packages your app into a distributable release. Creates installers, portable versions, and ZIP archives for Windows.',
    inputFields: ['Version number', 'Release notes', 'Platform'],
    outputArtifactType: 'build-plan',
    requiredPermissions: ['file_read', 'file_write', 'terminal_write'],
    examples: ['Build a beta release for testers', 'Create a portable version of the app'],
    relatedTemplates: ['generate-brand-assets'],
    testStatus: 'partial',
    category: 'general',
  },
]
