/**
 * Vibeforge — Skills & Agents Page
 *
 * Two-tab layout:
 *   Beginner — 10 canonical skills + 7 beginner agents, concept strip, action buttons
 *   Advanced — all agents + full VoltAgent external catalog (search + filters)
 *
 * Action buttons on each card:
 *   "Use in Build" → navigate to Studio with example prompt pre-filled
 *   "Copy"         → copy example prompt to clipboard
 */

import React, { useState, useMemo, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Search, ExternalLink, Copy, ArrowRight,
  Globe, Shield, AlertTriangle, CheckCircle, Clock, Sparkles,
  Layers, BookOpen, X, Lightbulb, Code2, Zap, Bot,
  Hammer, Bug, Monitor, Palette, Stethoscope, MessageSquare,
  ChevronDown, ChevronRight as ChevronRightIcon, Info
} from 'lucide-react'
import { EmptyState } from '../components/shared/EmptyState'
import { SKILL_CATEGORIES } from '../../../shared/external-skill-sources'
import type { SkillCategory, ExternalSkillEntry } from '../../../shared/external-skill-sources'
import { CANONICAL_SKILLS, CURATED_SKILLS } from '../../../shared/curated-skills'
import type { CuratedSkill } from '../../../shared/curated-skills'
import { AGENT_EDUCATION } from '../../../shared/agent-education'
import type { AgentEducation } from '../../../shared/agent-education'
// @ts-ignore — auto-generated by scripts/import-voltagent-awesome-skills.mjs
import { voltagentSkills } from '../../../shared/data/voltagent-awesome-skills.generated'

type ViewTab = 'beginner' | 'advanced'

// ─── Icon maps ────────────────────────────────────────────────────────────────

const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  'web-app-builder': <Globe size={13} />,
  'frontend-design': <Layers size={13} />,
  'webapp-testing': <Code2 size={13} />,
  'mcp-builder': <Zap size={13} />,
  'mobile-testing': <Globe size={13} />,
  'api-testing': <Code2 size={13} />,
  'cicd-pipeline': <Zap size={13} />,
  'security-review': <Shield size={13} />,
  'brand-guidelines': <Layers size={13} />,
  'theme-factory': <Layers size={13} />,
  'documentation': <BookOpen size={13} />,
  'spreadsheet-pdf': <BookOpen size={13} />,
  'ai-development': <Sparkles size={13} />,
  'cloud-deploy': <Globe size={13} />,
  'database': <Layers size={13} />,
  'authentication': <Shield size={13} />,
  'browser-automation': <Globe size={13} />,
  'code-quality': <CheckCircle size={13} />,
  'agent-orchestration': <Zap size={13} />,
  'other': <Layers size={13} />,
}

const AGENT_ICON_MAP: Record<string, React.ReactNode> = {
  Hammer: <Hammer size={16} />,
  Monitor: <Monitor size={16} />,
  Palette: <Palette size={16} />,
  Bug: <Bug size={16} />,
  Stethoscope: <Stethoscope size={16} />,
  BookOpen: <BookOpen size={16} />,
  MessageSquare: <MessageSquare size={16} />,
  Shield: <Shield size={16} />,
  Paintbrush: <Palette size={16} />,
  TestTube: <Code2 size={16} />,
  GitBranch: <Code2 size={16} />,
  Wand: <Sparkles size={16} />,
  Search: <Search size={16} />,
  BarChart: <Layers size={16} />,
  Share2: <Globe size={16} />,
  GraduationCap: <BookOpen size={16} />,
}

const LICENSE_LABELS: Record<string, { label: string; color: string }> = {
  'known-open': { label: 'Open License', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  'known-proprietary': { label: 'Proprietary', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  'unknown': { label: 'Unknown License', color: 'bg-[var(--ivory-surface)] text-[var(--ivory-text-3)] border-[var(--ivory-border)]' },
  'needs-review': { label: 'Needs Review', color: 'bg-red-50 text-red-700 border-red-200' },
}

const RISK_LABELS: Record<string, { label: string; icon: React.ReactNode }> = {
  'safe': { label: 'Safe', icon: <CheckCircle size={10} className="text-emerald-600" /> },
  'caution': { label: 'Caution', icon: <AlertTriangle size={10} className="text-amber-600" /> },
  'destructive': { label: 'Destructive', icon: <AlertTriangle size={10} className="text-red-600" /> },
}

// ─── Concept strip ─────────────────────────────────────────────────────────────

const CONCEPTS = [
  { label: 'Agent', meaning: 'Role', detail: 'A focused AI persona with a specific job' },
  { label: 'Skill', meaning: 'Workflow', detail: 'A repeatable sequence producing a specific output' },
  { label: 'Tool', meaning: 'Action', detail: 'A single API call, command, or file operation' },
  { label: 'MCP', meaning: 'Connector', detail: 'Connects Vibeforge to an external service' },
]

function ConceptStrip({ onDismiss }: { onDismiss: () => void }): React.ReactElement {
  return (
    <div className="mx-6 mt-4 mb-1 p-3 rounded-2xl bg-[var(--ivory-accent-light)]/40 border border-[var(--ivory-accent)]/15 flex items-start gap-3" data-testid="concept-strip">
      <Info size={14} className="text-[var(--ivory-accent)] shrink-0 mt-0.5" />
      <div className="flex-1 min-w-0">
        <div className="flex flex-wrap gap-3">
          {CONCEPTS.map(c => (
            <span key={c.label} className="inline-flex items-center gap-1 text-[11px]" title={c.detail}>
              <span className="font-bold text-[var(--ivory-text)]">{c.label}</span>
              <span className="text-[var(--ivory-text-3)]">=</span>
              <span className="font-semibold text-[var(--ivory-accent)]">{c.meaning}</span>
            </span>
          ))}
        </div>
      </div>
      <button
        type="button"
        onClick={onDismiss}
        className="p-0.5 text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] cursor-pointer shrink-0"
        aria-label="Dismiss"
      >
        <X size={13} />
      </button>
    </div>
  )
}

// ─── Main page ─────────────────────────────────────────────────────────────────

export function SkillsPage(): React.ReactElement {
  const navigate = useNavigate()
  const [tab, setTab] = useState<ViewTab>('beginner')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<SkillCategory | 'all'>('all')
  const [selectedProvider, setSelectedProvider] = useState<string>('all')
  const [selectedAdaptSkill, setSelectedAdaptSkill] = useState<string | null>(null)
  const [conceptDismissed, setConceptDismissed] = useState(() =>
    localStorage.getItem('vb_concept_strip_dismissed') === 'true'
  )
  const [copiedId, setCopiedId] = useState<string | null>(null)

  const externalEntries: ExternalSkillEntry[] = voltagentSkills || []

  const beginnerAgents = AGENT_EDUCATION.filter(a => a.tier === 'beginner')
  const allAgents = AGENT_EDUCATION

  // Computed providers for advanced filter
  const providers = useMemo(() => {
    const set = new Set<string>()
    for (const e of externalEntries) set.add(e.provider)
    return [...set].sort()
  }, [externalEntries])

  // Filtered external skills (advanced tab)
  const filteredExternal = useMemo(() => {
    let result = externalEntries
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      result = result.filter(e =>
        e.name.toLowerCase().includes(q) ||
        e.description.toLowerCase().includes(q) ||
        e.provider.toLowerCase().includes(q) ||
        e.tags.some(t => t.includes(q))
      )
    }
    if (selectedCategory !== 'all') result = result.filter(e => e.category === selectedCategory)
    if (selectedProvider !== 'all') result = result.filter(e => e.provider === selectedProvider)
    return result
  }, [externalEntries, searchQuery, selectedCategory, selectedProvider])

  // Filtered curated skills (advanced tab all, beginner tab canonical only)
  const filteredCurated = useMemo(() => {
    const source = tab === 'beginner' ? CANONICAL_SKILLS : CURATED_SKILLS
    if (!searchQuery && selectedCategory === 'all') return source
    const q = searchQuery.toLowerCase()
    return source.filter(s =>
      (!searchQuery || s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q)) &&
      (selectedCategory === 'all' || s.category === selectedCategory)
    )
  }, [searchQuery, selectedCategory, tab])

  // Filtered agents
  const filteredAgents = useMemo(() => {
    const source = tab === 'beginner' ? beginnerAgents : allAgents
    if (!searchQuery) return source
    const q = searchQuery.toLowerCase()
    return source.filter(a =>
      a.name.toLowerCase().includes(q) ||
      a.beginnerExplanation.toLowerCase().includes(q)
    )
  }, [searchQuery, tab, beginnerAgents, allAgents])

  const handleDismissConcept = useCallback(() => {
    setConceptDismissed(true)
    localStorage.setItem('vb_concept_strip_dismissed', 'true')
  }, [])

  const handleCopyPrompt = useCallback((id: string, prompt: string) => {
    navigator.clipboard?.writeText(prompt).catch(() => {})
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
  }, [])

  const handleUseSkill = useCallback((prompt: string) => {
    sessionStorage.setItem('vb_prefill_prompt', prompt)
    navigate('/studio')
  }, [navigate])

  const clearFilters = useCallback(() => {
    setSearchQuery('')
    setSelectedCategory('all')
    setSelectedProvider('all')
  }, [])

  const hasFilters = searchQuery || selectedCategory !== 'all' || selectedProvider !== 'all'

  return (
    <div className="flex flex-col h-full bg-[var(--ivory-bg)]" data-testid="skills-page">
      {/* Header */}
      <div className="px-6 pt-5 pb-0 shrink-0">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-[18px] font-semibold text-[var(--ivory-text)] flex items-center gap-2 select-none">
              <Bot size={18} className="text-[var(--ivory-accent)]" />
              Skills &amp; Agents
            </h2>
            <p className="text-[11px] text-[var(--ivory-text-3)] mt-0.5">
              {tab === 'beginner'
                ? `${CANONICAL_SKILLS.length} skills · ${beginnerAgents.length} agents — ready to use`
                : `${CURATED_SKILLS.length} curated · ${externalEntries.length.toLocaleString()} external skills`}
            </p>
          </div>
          {/* Tab bar */}
          <div className="flex items-center gap-1 p-1 rounded-xl bg-[var(--ivory-surface)] border border-[var(--ivory-border)]">
            {(['beginner', 'advanced'] as ViewTab[]).map(t => (
              <button
                key={t}
                type="button"
                onClick={() => setTab(t)}
                data-testid={`tab-${t}`}
                className={`px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-colors cursor-pointer capitalize ${
                  tab === t
                    ? 'bg-[var(--ivory-elevated)] text-[var(--ivory-text)] shadow-sm border border-[var(--ivory-border)]'
                    : 'text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)]'
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Concept strip (beginner tab only) */}
      {tab === 'beginner' && !conceptDismissed && (
        <ConceptStrip onDismiss={handleDismissConcept} />
      )}

      {/* Search & Filters */}
      <div className="px-6 py-3 flex items-center gap-3 flex-wrap shrink-0 border-b border-[var(--ivory-border)]">
        <div className="relative flex-1 min-w-[200px] max-w-[320px]">
          <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--ivory-text-3)]" />
          <input
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search skills, agents, or descriptions…"
            className="w-full pl-8 pr-3 py-1.5 text-[12px] rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text)] placeholder-[var(--ivory-text-3)]/60 focus:outline-none focus:border-[var(--ivory-accent)]/40 transition-colors"
            data-testid="skills-search-input"
          />
          {searchQuery && (
            <button type="button" onClick={() => setSearchQuery('')} className="absolute right-2 top-1/2 -translate-y-1/2 p-0.5 text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] cursor-pointer">
              <X size={12} />
            </button>
          )}
        </div>

        <select
          value={selectedCategory}
          onChange={e => setSelectedCategory(e.target.value as SkillCategory | 'all')}
          className="px-2.5 py-1.5 text-[11px] font-semibold rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text-2)] cursor-pointer outline-none focus:border-[var(--ivory-accent)]/40"
          data-testid="skills-category-filter"
        >
          <option value="all">All Categories</option>
          {SKILL_CATEGORIES.map(cat => (
            <option key={cat.id} value={cat.id}>{cat.label}</option>
          ))}
        </select>

        {tab === 'advanced' && (
          <select
            value={selectedProvider}
            onChange={e => setSelectedProvider(e.target.value)}
            className="px-2.5 py-1.5 text-[11px] font-semibold rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text-2)] cursor-pointer outline-none focus:border-[var(--ivory-accent)]/40 max-w-[180px]"
            data-testid="skills-provider-filter"
          >
            <option value="all">All Providers ({providers.length})</option>
            {providers.map(p => (
              <option key={p} value={p}>{p}</option>
            ))}
          </select>
        )}

        {hasFilters && (
          <button type="button" onClick={clearFilters} className="px-2.5 py-1.5 text-[11px] font-semibold text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] rounded-xl hover:bg-[var(--ivory-surface)] transition-colors cursor-pointer">
            Clear filters
          </button>
        )}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-8">
        {tab === 'beginner' ? (
          <>
            {/* Beginner: Agents */}
            <section>
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3 flex items-center gap-1.5">
                <Bot size={12} /> Agents — choose a specialist
              </h3>
              {filteredAgents.length === 0 ? (
                <EmptyState icon={<Search size={28} strokeWidth={1.5} />} title="No matching agents" description="Try adjusting your search." />
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                  {filteredAgents.map(agent => (
                    <AgentCard
                      key={agent.id}
                      agent={agent}
                      copiedId={copiedId}
                      onCopyPrompt={handleCopyPrompt}
                      onUse={handleUseSkill}
                    />
                  ))}
                </div>
              )}
            </section>

            {/* Beginner: Canonical skills */}
            <section>
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3 flex items-center gap-1.5">
                <Sparkles size={12} /> Skills — ready-to-run workflows
              </h3>
              {filteredCurated.length === 0 ? (
                <EmptyState icon={<Search size={28} strokeWidth={1.5} />} title="No matching skills" description="Try adjusting your search or category filter." />
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {filteredCurated.map(skill => (
                    <CanonicalSkillCard
                      key={skill.id}
                      skill={skill}
                      copiedId={copiedId}
                      onCopyPrompt={handleCopyPrompt}
                      onUse={handleUseSkill}
                    />
                  ))}
                </div>
              )}
            </section>
          </>
        ) : (
          <>
            {/* Advanced: All agents */}
            <section>
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3 flex items-center gap-1.5">
                <Bot size={12} /> All Agents ({filteredAgents.length})
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                {filteredAgents.map(agent => (
                  <AgentCard
                    key={agent.id}
                    agent={agent}
                    copiedId={copiedId}
                    onCopyPrompt={handleCopyPrompt}
                    onUse={handleUseSkill}
                  />
                ))}
              </div>
            </section>

            {/* Advanced: Curated skill library */}
            <section>
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3 flex items-center gap-1.5">
                <Sparkles size={12} /> Vibeforge Skill Library ({filteredCurated.length})
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredCurated.map(skill => (
                  <CanonicalSkillCard
                    key={skill.id}
                    skill={skill}
                    copiedId={copiedId}
                    onCopyPrompt={handleCopyPrompt}
                    onUse={handleUseSkill}
                  />
                ))}
              </div>
            </section>

            {/* Advanced: External VoltAgent catalog */}
            <section>
              <h3 className="text-[11px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3 flex items-center gap-1.5">
                <Globe size={12} /> External Skills — VoltAgent Catalog ({filteredExternal.length.toLocaleString()})
                {hasFilters && <span className="text-[var(--ivory-text-3)] font-normal">(filtered)</span>}
              </h3>
              {filteredExternal.length === 0 ? (
                <EmptyState icon={<Search size={28} strokeWidth={1.5} />} title="No matching skills" description={hasFilters ? 'Try adjusting your search or filters.' : 'No skills loaded. Run the importer script.'} />
              ) : (
                <>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                    {filteredExternal.slice(0, 300).map(skill => (
                      <ExternalSkillCard
                        key={skill.id}
                        skill={skill}
                        onAdapt={() => setSelectedAdaptSkill(skill.id)}
                        onCopyLink={() => navigator.clipboard?.writeText(skill.url)}
                        isAdapting={selectedAdaptSkill === skill.id}
                      />
                    ))}
                  </div>
                  {filteredExternal.length > 300 && (
                    <p className="text-[11px] text-[var(--ivory-text-3)] text-center mt-4">
                      Showing 300 of {filteredExternal.length.toLocaleString()} results. Use filters to narrow down.
                    </p>
                  )}
                </>
              )}
            </section>
          </>
        )}
      </div>

      {/* Adapt Modal */}
      {selectedAdaptSkill && (
        <AdaptFlowModal skillId={selectedAdaptSkill} onClose={() => setSelectedAdaptSkill(null)} />
      )}
    </div>
  )
}

// ─── Agent Card ───────────────────────────────────────────────────────────────

function AgentCard({
  agent,
  copiedId,
  onCopyPrompt,
  onUse,
}: {
  agent: AgentEducation
  copiedId: string | null
  onCopyPrompt: (id: string, prompt: string) => void
  onUse: (prompt: string) => void
}): React.ReactElement {
  const icon = AGENT_ICON_MAP[agent.icon] ?? <Bot size={16} />
  const isActive = true // agents are always active
  const tierColor = agent.tier === 'beginner'
    ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
    : 'bg-[var(--ivory-surface)] text-[var(--ivory-text-3)] border-[var(--ivory-border)]'

  return (
    <div
      className="rounded-2xl border border-[var(--ivory-border)] bg-[var(--ivory-elevated)] shadow-[var(--shadow-sm)] hover:shadow-[var(--shadow-md)] transition-shadow p-4 flex flex-col gap-2"
      data-testid="agent-card"
    >
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-[var(--ivory-accent)]">{icon}</span>
          <h3 className="text-[13px] font-semibold text-[var(--ivory-text)] truncate">{agent.name}</h3>
        </div>
        <span className={`inline-flex items-center px-1.5 py-0.5 rounded-full text-[9px] font-semibold border shrink-0 ${tierColor}`}>
          {agent.tier}
        </span>
      </div>
      <p className="text-[11px] text-[var(--ivory-text-2)] leading-relaxed line-clamp-2">{agent.beginnerExplanation}</p>
      {agent.isDestructive && (
        <span className="inline-flex items-center gap-1 text-[9px] text-amber-700">
          <AlertTriangle size={9} /> Destructive actions possible
        </span>
      )}
      {/* Actions */}
      <div className="flex items-center gap-1.5 pt-1 border-t border-[var(--ivory-border)]/40 mt-auto">
        <button
          type="button"
          onClick={() => onUse(agent.examplePrompt)}
          disabled={!isActive}
          className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-[var(--ivory-bronze)] text-white hover:bg-[var(--ivory-bronze-hover)] text-[10px] font-semibold transition-colors cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          data-testid="agent-use-btn"
        >
          <Zap size={9} /> Use in Build
        </button>
        <button
          type="button"
          onClick={() => onCopyPrompt(agent.id, agent.examplePrompt)}
          className="ml-auto inline-flex items-center gap-1 px-2 py-1 rounded-full border border-[var(--ivory-border)] text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] text-[10px] font-semibold transition-colors cursor-pointer"
          data-testid="agent-copy-btn"
        >
          {copiedId === agent.id ? <CheckCircle size={9} className="text-emerald-600" /> : <Copy size={9} />}
          {copiedId === agent.id ? 'Copied' : 'Copy'}
        </button>
      </div>
    </div>
  )
}

// ─── Canonical Skill Card ─────────────────────────────────────────────────────

function CanonicalSkillCard({
  skill,
  copiedId,
  onCopyPrompt,
  onUse,
}: {
  skill: CuratedSkill
  copiedId: string | null
  onCopyPrompt: (id: string, prompt: string) => void
  onUse: (prompt: string) => void
}): React.ReactElement {
  const catInfo = SKILL_CATEGORIES.find(c => c.id === skill.category)
  const isActive = skill.status === 'active'
  const statusColors = {
    active: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    planned: 'bg-amber-50 text-amber-700 border-amber-200',
    placeholder: 'bg-[var(--ivory-surface)] text-[var(--ivory-text-3)] border-[var(--ivory-border)]',
  }

  return (
    <div
      className="rounded-2xl border border-[var(--ivory-accent)]/15 bg-[var(--ivory-elevated)] shadow-[var(--shadow-md)] p-5 flex flex-col gap-3 ring-1 ring-[var(--ivory-accent)]/5"
      data-testid="curated-skill-card"
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 mb-1">
            {CATEGORY_ICONS[skill.category] || <Layers size={13} className="text-[var(--ivory-text-3)]" />}
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)]">
              {catInfo?.label || skill.category}
            </span>
          </div>
          <h3 className="text-[14px] font-semibold text-[var(--ivory-text)]">{skill.name}</h3>
        </div>
        <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-semibold border ${statusColors[skill.status]} shrink-0`}>
          {skill.status === 'active' ? <CheckCircle size={9} /> : skill.status === 'planned' ? <Clock size={9} /> : <AlertTriangle size={9} />}
          {skill.status === 'active' ? 'Ready' : skill.status === 'planned' ? 'Coming soon' : 'Placeholder'}
        </span>
      </div>

      {/* Description */}
      <p className="text-[11px] text-[var(--ivory-text-2)] leading-relaxed">{skill.description}</p>

      {/* Capabilities */}
      {skill.capabilities.length > 0 && (
        <ul className="space-y-0.5">
          {skill.capabilities.slice(0, 3).map((cap, i) => (
            <li key={i} className="text-[10px] text-[var(--ivory-text-2)] flex items-start gap-1.5">
              <CheckCircle size={9} className="text-emerald-500 shrink-0 mt-0.5" />
              {cap}
            </li>
          ))}
        </ul>
      )}

      {/* Actions */}
      <div className="flex items-center gap-1.5 mt-auto pt-2 border-t border-[var(--ivory-border)]/40">
        {isActive ? (
          <>
            <button
              type="button"
              onClick={() => onUse(skill.examplePrompt)}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-[var(--ivory-bronze)] text-white hover:bg-[var(--ivory-bronze-hover)] text-[10px] font-semibold transition-colors cursor-pointer"
              data-testid="skill-use-btn"
            >
              <Zap size={10} /> Use in Build
            </button>
            <button
              type="button"
              onClick={() => onCopyPrompt(skill.id, skill.examplePrompt)}
              className="ml-auto inline-flex items-center gap-1 px-2.5 py-1.5 rounded-full border border-[var(--ivory-border)] text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] text-[10px] font-semibold transition-colors cursor-pointer"
              data-testid="skill-copy-btn"
            >
              {copiedId === skill.id ? <CheckCircle size={9} className="text-emerald-600" /> : <Copy size={9} />}
              {copiedId === skill.id ? 'Copied' : 'Copy'}
            </button>
          </>
        ) : (
          <span className="text-[10px] font-medium text-[var(--ivory-text-3)] px-3 py-1.5 rounded-full bg-[var(--ivory-surface)] border border-dashed border-[var(--ivory-border)]">
            {skill.status === 'planned' ? 'Coming soon' : 'Placeholder'}
          </span>
        )}
      </div>
    </div>
  )
}

// ─── External Skill Card ──────────────────────────────────────────────────────

function ExternalSkillCard({
  skill,
  onAdapt,
  onCopyLink,
  isAdapting,
}: {
  skill: ExternalSkillEntry
  onAdapt: () => void
  onCopyLink: () => void
  isAdapting: boolean
}): React.ReactElement {
  const catInfo = SKILL_CATEGORIES.find(c => c.id === skill.category)
  const licenseInfo = LICENSE_LABELS[skill.licenseStatus] || LICENSE_LABELS.unknown
  const riskInfo = RISK_LABELS[skill.riskLevel] || RISK_LABELS.safe

  return (
    <div className="rounded-2xl border border-[var(--ivory-border)] bg-[var(--ivory-elevated)] shadow-[var(--shadow-sm)] hover:shadow-[var(--shadow-md)] transition-shadow p-4 flex flex-col gap-3" data-testid="external-skill-card">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 mb-1">
            {CATEGORY_ICONS[skill.category] || <Layers size={13} className="text-[var(--ivory-text-3)]" />}
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)]">
              {catInfo?.label || skill.category}
            </span>
          </div>
          <h3 className="text-[13px] font-semibold text-[var(--ivory-text)] truncate">{skill.name}</h3>
          <span className="text-[10px] text-[var(--ivory-text-3)] font-mono">{skill.provider}</span>
        </div>
        <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-semibold border ${licenseInfo.color}`}>
          {licenseInfo.label}
        </span>
      </div>
      <p className="text-[11px] text-[var(--ivory-text-2)] leading-relaxed line-clamp-3">{skill.description}</p>
      {skill.tags.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {skill.tags.slice(0, 4).map(tag => (
            <span key={tag} className="px-1.5 py-0.5 rounded-full bg-[var(--ivory-surface)] text-[9px] font-medium text-[var(--ivory-text-3)] border border-[var(--ivory-border)]/60">
              {tag}
            </span>
          ))}
        </div>
      )}
      <div className="flex items-center gap-1.5 text-[9px] text-[var(--ivory-text-3)]">
        {riskInfo.icon}
        {riskInfo.label}
      </div>
      <div className="flex items-center gap-2 mt-auto pt-2 border-t border-[var(--ivory-border)]/40">
        <a href={skill.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--ivory-accent)] hover:underline cursor-pointer" data-testid="skill-source-link">
          <ExternalLink size={10} /> Source
        </a>
        <button type="button" onClick={onCopyLink} className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] transition-colors cursor-pointer">
          <Copy size={10} /> Copy link
        </button>
        <button type="button" onClick={onAdapt} disabled={isAdapting} className="ml-auto inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-[var(--ivory-accent-light)] text-[var(--ivory-accent)] hover:bg-[var(--ivory-accent-light)]/80 text-[10px] font-semibold transition-colors cursor-pointer disabled:opacity-50">
          <ArrowRight size={10} /> Adapt
        </button>
      </div>
    </div>
  )
}

// ─── Adapt Flow Modal ─────────────────────────────────────────────────────────

function AdaptFlowModal({ skillId, onClose }: { skillId: string; onClose: () => void }): React.ReactElement {
  const [copied, setCopied] = useState(false)
  const adaptPrompt = `Create an original Vibeforge skill inspired by external skill "${skillId}".

Requirements:
1. Write an original SKILL.md following Vibeforge skill conventions
2. Use the Vibeforge calm ivory design system (#FAF7F2, #C75B39, Inter font, serif headings)
3. Define clear capabilities, permissions, and usage examples
4. Do NOT copy content from the external source — create an original implementation
5. Include a "Inspired by" section with attribution to the source
6. Add "Adapted for Vibeforge" badge

The skill should be production-quality and follow security best practices.`

  const handleCopy = () => {
    navigator.clipboard?.writeText(adaptPrompt).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20" onClick={onClose}>
      <div className="bg-[var(--ivory-elevated)] border border-[var(--ivory-border)] rounded-[24px] shadow-[var(--shadow-xl)] p-6 max-w-lg w-full mx-4 max-h-[80vh] overflow-y-auto" onClick={e => e.stopPropagation()} data-testid="adapt-skill-modal">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-[15px] font-semibold text-[var(--ivory-text)] flex items-center gap-2">
            <Lightbulb size={16} className="text-[var(--ivory-accent)]" />
            Adapt into Vibeforge Skill
          </h3>
          <button type="button" onClick={onClose} className="p-1 text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] cursor-pointer"><X size={16} /></button>
        </div>
        <div className="space-y-4">
          <div className="p-3 rounded-xl bg-amber-50/40 border border-amber-200/30">
            <div className="flex gap-2 items-start">
              <AlertTriangle size={13} className="text-amber-600/70 shrink-0 mt-0.5" />
              <div className="text-[10px] leading-relaxed text-amber-800/80">
                <span className="font-semibold">Original content only.</span> The adaptation creates an original Vibeforge skill inspired by "{skillId}" — it does NOT copy the source content.
              </div>
            </div>
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] block mb-1.5">Adaptation Prompt</span>
            <div className="rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] p-3">
              <pre className="text-[11px] font-mono text-[var(--ivory-text-2)] leading-relaxed whitespace-pre-wrap break-all">{adaptPrompt}</pre>
            </div>
          </div>
          <div className="flex gap-2">
            <button type="button" onClick={handleCopy} className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[var(--ivory-accent)] text-white hover:bg-[var(--ivory-accent-hover)] text-[11px] font-semibold transition-colors cursor-pointer">
              {copied ? <CheckCircle size={12} /> : <Copy size={12} />}
              {copied ? 'Copied!' : 'Copy to composer'}
            </button>
            <button type="button" onClick={onClose} className="px-4 py-2 rounded-xl border border-[var(--ivory-border)] text-[var(--ivory-text-2)] hover:text-[var(--ivory-text)] text-[11px] font-semibold transition-colors cursor-pointer">
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
