/**
 * Aureon Desk — Skill Explorer Page
 *
 * Browse, search, and filter external skills from VoltAgent/awesome-agent-skills
 * and Aureon's curated skill starter set. Skills can be inspected, adapted, or
 * used as inspiration for custom Aureon skills.
 */

import React, { useState, useMemo, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Search, ExternalLink, Copy, ArrowRight,
  Globe, Shield, AlertTriangle, CheckCircle, Clock, Sparkles,
  Layers, BookOpen, X, Lightbulb, Code2, Zap
} from 'lucide-react'
import { EmptyState } from '../components/shared/EmptyState'
import { SKILL_CATEGORIES } from '../../../shared/external-skill-sources'
import type { SkillCategory, ExternalSkillEntry } from '../../../shared/external-skill-sources'
import { CURATED_SKILLS } from '../../../shared/curated-skills'
import type { CuratedSkill } from '../../../shared/curated-skills'
// @ts-ignore — auto-generated by scripts/import-voltagent-awesome-skills.mjs
import { voltagentSkills } from '../../../shared/data/voltagent-awesome-skills.generated'

type ViewMode = 'all' | 'curated'

const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  'web-app-builder': <Globe size={14} />,
  'frontend-design': <Layers size={14} />,
  'webapp-testing': <Code2 size={14} />,
  'mcp-builder': <Zap size={14} />,
  'mobile-testing': <Globe size={14} />,
  'api-testing': <Code2 size={14} />,
  'cicd-pipeline': <Zap size={14} />,
  'security-review': <Shield size={14} />,
  'brand-guidelines': <Layers size={14} />,
  'theme-factory': <Layers size={14} />,
  'documentation': <BookOpen size={14} />,
  'spreadsheet-pdf': <BookOpen size={14} />,
  'ai-development': <Sparkles size={14} />,
  'cloud-deploy': <Globe size={14} />,
  'database': <Layers size={14} />,
  'authentication': <Shield size={14} />,
  'browser-automation': <Globe size={14} />,
  'code-quality': <CheckCircle size={14} />,
  'agent-orchestration': <Zap size={14} />,
  'other': <Layers size={14} />,
}

const LICENSE_LABELS: Record<string, { label: string; color: string }> = {
  'known-open': { label: 'Open License', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  'known-proprietary': { label: 'Proprietary', color: 'bg-amber-50 text-amber-700 border-amber-200' },
  'unknown': { label: 'Unknown License', color: 'bg-[var(--ivory-surface)] text-[var(--ivory-text-3)] border-[var(--ivory-border)]' },
  'needs-review': { label: 'Needs Review', color: 'bg-red-50 text-red-700 border-red-200' },
}

const RISK_LABELS: Record<string, { label: string; icon: React.ReactNode }> = {
  'safe': { label: 'Safe', icon: <CheckCircle size={10} className="text-emerald-600" /> },
  'caution': { label: 'Caution', icon: <AlertTriangle size={10} className="text-amber-600" /> },
  'destructive': { label: 'Destructive', icon: <AlertTriangle size={10} className="text-red-600" /> },
}

export function SkillsPage(): React.ReactElement {
  const navigate = useNavigate()
  const [viewMode, setViewMode] = useState<ViewMode>('all')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<SkillCategory | 'all'>('all')
  const [selectedProvider, setSelectedProvider] = useState<string>('all')
  const [selectedAdaptSkill, setSelectedAdaptSkill] = useState<string | null>(null)
  const externalEntries: ExternalSkillEntry[] = voltagentSkills || []

  // Compute unique providers
  const providers = useMemo(() => {
    const set = new Set<string>()
    for (const e of externalEntries) set.add(e.provider)
    return [...set].sort()
  }, [externalEntries])

  // Filter skills
  const filteredExternal = useMemo(() => {
    let result = externalEntries
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      result = result.filter(e =>
        e.name.toLowerCase().includes(q) ||
        e.description.toLowerCase().includes(q) ||
        e.provider.toLowerCase().includes(q) ||
        e.tags.some(t => t.includes(q))
      )
    }
    if (selectedCategory !== 'all') {
      result = result.filter(e => e.category === selectedCategory)
    }
    if (selectedProvider !== 'all') {
      result = result.filter(e => e.provider === selectedProvider)
    }
    return result
  }, [externalEntries, searchQuery, selectedCategory, selectedProvider])

  const filteredCurated = useMemo(() => {
    let result = CURATED_SKILLS
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      result = result.filter(s =>
        s.name.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q)
      )
    }
    if (selectedCategory !== 'all') {
      result = result.filter(s => s.category === selectedCategory)
    }
    return result
  }, [searchQuery, selectedCategory])

  const handleAdapt = useCallback((skill: CuratedSkill | ExternalSkillEntry) => {
    setSelectedAdaptSkill(skill.id)
  }, [])

  const handleCopyLink = useCallback((url: string) => {
    navigator.clipboard?.writeText(url)
  }, [])

  const clearFilters = useCallback(() => {
    setSearchQuery('')
    setSelectedCategory('all')
    setSelectedProvider('all')
  }, [])

  const hasFilters = searchQuery || selectedCategory !== 'all' || selectedProvider !== 'all'

  return (
    <div className="flex flex-col h-full bg-[var(--ivory-bg)]" data-testid="skills-page">
      {/* Header */}
      <div className="px-6 py-4 border-b border-[var(--ivory-border)] flex items-center justify-between shrink-0 bg-[var(--ivory-elevated)]/80">
        <div>
          <h2 className="text-[17px] font-semibold text-[var(--ivory-text)] flex items-center gap-2 select-none">
            <Sparkles size={18} className="text-[var(--ivory-accent)]" />
            Skills & Agents
          </h2>
          <p className="text-xs text-[var(--ivory-text-3)] mt-0.5">
            {viewMode === 'curated'
              ? 'Aureon original skill starter set — ready to use'
              : `${externalEntries.length.toLocaleString()} external skills from VoltAgent/awesome-agent-skills — browse, adapt, or create`}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setViewMode('curated')}
            className={`px-3 py-1.5 rounded-full text-[11px] font-semibold transition-colors cursor-pointer ${
              viewMode === 'curated'
                ? 'bg-[var(--ivory-accent-light)] text-[var(--ivory-accent)] border border-[var(--ivory-accent)]/20'
                : 'text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] border border-transparent'
            }`}
          >
            Curated ({CURATED_SKILLS.length})
          </button>
          <button
            type="button"
            onClick={() => setViewMode('all')}
            className={`px-3 py-1.5 rounded-full text-[11px] font-semibold transition-colors cursor-pointer ${
              viewMode === 'all'
                ? 'bg-[var(--ivory-accent-light)] text-[var(--ivory-accent)] border border-[var(--ivory-accent)]/20'
                : 'text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] border border-transparent'
            }`}
          >
            All ({externalEntries.length.toLocaleString()})
          </button>
        </div>
      </div>

      {/* Search & Filters */}
      <div className="px-6 py-3 border-b border-[var(--ivory-border)] flex items-center gap-3 flex-wrap shrink-0 bg-[var(--ivory-surface)]/30">
        <div className="relative flex-1 min-w-[200px] max-w-[360px]">
          <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--ivory-text-3)]" />
          <input
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Search skills by name, description, or tag..."
            className="w-full pl-8 pr-3 py-1.5 text-[12px] rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text)] placeholder-[var(--ivory-text-3)]/60 focus:outline-none focus:border-[var(--ivory-accent)]/40 transition-colors"
            data-testid="skills-search-input"
          />
          {searchQuery && (
            <button
              type="button"
              onClick={() => setSearchQuery('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 p-0.5 text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] cursor-pointer"
            >
              <X size={12} />
            </button>
          )}
        </div>

        <select
          value={selectedCategory}
          onChange={e => setSelectedCategory(e.target.value as SkillCategory | 'all')}
          className="px-2.5 py-1.5 text-[11px] font-semibold rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text-2)] cursor-pointer outline-none focus:border-[var(--ivory-accent)]/40"
          data-testid="skills-category-filter"
        >
          <option value="all">All Categories</option>
          {SKILL_CATEGORIES.map(cat => (
            <option key={cat.id} value={cat.id}>{cat.label}</option>
          ))}
        </select>

        {viewMode === 'all' && (
          <select
            value={selectedProvider}
            onChange={e => setSelectedProvider(e.target.value)}
            className="px-2.5 py-1.5 text-[11px] font-semibold rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] text-[var(--ivory-text-2)] cursor-pointer outline-none focus:border-[var(--ivory-accent)]/40 max-w-[200px]"
            data-testid="skills-provider-filter"
          >
            <option value="all">All Providers ({providers.length})</option>
            {providers.map(p => (
              <option key={p} value={p}>{p}</option>
            ))}
          </select>
        )}

        {hasFilters && (
          <button
            type="button"
            onClick={clearFilters}
            className="px-2.5 py-1.5 text-[11px] font-semibold text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] rounded-xl hover:bg-[var(--ivory-surface)] transition-colors cursor-pointer"
          >
            Clear filters
          </button>
        )}
      </div>

      {/* Skill Cards Grid */}
      <div className="flex-1 overflow-y-auto p-6">
        {viewMode === 'curated' ? (
          filteredCurated.length === 0 ? (
            <EmptyState
              icon={<Search size={32} strokeWidth={1.5} />}
              title="No matching curated skills"
              description="Try adjusting your search or category filter."
            />
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredCurated.map(skill => (
                <CuratedSkillCard
                  key={skill.id}
                  skill={skill}
                  onAdapt={() => handleAdapt(skill)}
                  isAdapting={selectedAdaptSkill === skill.id}
                />
              ))}
            </div>
          )
        ) : filteredExternal.length === 0 ? (
          <EmptyState
            icon={<Search size={32} strokeWidth={1.5} />}
            title="No matching skills"
            description={hasFilters ? 'Try adjusting your search or filters.' : 'No skills loaded. Run the importer script to populate the catalog.'}
          />
        ) : (
          <>
            <div className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] mb-3">
              {filteredExternal.length.toLocaleString()} skills
              {hasFilters && ' (filtered)'}
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {filteredExternal.slice(0, 500).map(skill => (
                <ExternalSkillCard
                  key={skill.id}
                  skill={skill}
                  onAdapt={() => handleAdapt(skill)}
                  onCopyLink={() => handleCopyLink(skill.url)}
                  isAdapting={selectedAdaptSkill === skill.id}
                />
              ))}
            </div>
            {filteredExternal.length > 500 && (
              <p className="text-[11px] text-[var(--ivory-text-3)] text-center mt-4">
                Showing 500 of {filteredExternal.length.toLocaleString()} matching skills. Use filters to narrow results.
              </p>
            )}
          </>
        )}
      </div>

      {/* Adapt Flow Modal */}
      {selectedAdaptSkill && (
        <AdaptFlowModal
          skillId={selectedAdaptSkill}
          onClose={() => setSelectedAdaptSkill(null)}
        />
      )}
    </div>
  )
}

/** External skill card from VoltAgent catalog */
function ExternalSkillCard({
  skill,
  onAdapt,
  onCopyLink,
  isAdapting,
}: {
  skill: ExternalSkillEntry
  onAdapt: () => void
  onCopyLink: () => void
  isAdapting: boolean
}): React.ReactElement {
  const catInfo = SKILL_CATEGORIES.find(c => c.id === skill.category)
  const licenseInfo = LICENSE_LABELS[skill.licenseStatus] || LICENSE_LABELS.unknown
  const riskInfo = RISK_LABELS[skill.riskLevel] || RISK_LABELS.safe

  return (
    <div className="rounded-2xl border border-[var(--ivory-border)] bg-[var(--ivory-elevated)] shadow-[var(--shadow-sm)] hover:shadow-[var(--shadow-md)] transition-shadow p-4 flex flex-col gap-3" data-testid="external-skill-card">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 mb-1">
            {CATEGORY_ICONS[skill.category] || <Layers size={14} className="text-[var(--ivory-text-3)]" />}
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)]">
              {catInfo?.label || skill.category}
            </span>
          </div>
          <h3 className="text-[13px] font-semibold text-[var(--ivory-text)] truncate">{skill.name}</h3>
          <span className="text-[10px] text-[var(--ivory-text-3)] font-mono">{skill.provider}</span>
        </div>
        <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-semibold border ${licenseInfo.color}`}>
          {licenseInfo.label}
        </span>
      </div>

      {/* Description */}
      <p className="text-[11px] text-[var(--ivory-text-2)] leading-relaxed line-clamp-3">{skill.description}</p>

      {/* Tags */}
      {skill.tags.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {skill.tags.slice(0, 5).map(tag => (
            <span key={tag} className="px-1.5 py-0.5 rounded-full bg-[var(--ivory-surface)] text-[9px] font-medium text-[var(--ivory-text-3)] border border-[var(--ivory-border)]/60">
              {tag}
            </span>
          ))}
        </div>
      )}

      {/* Risk badge */}
      <div className="flex items-center gap-1.5">
        <span className="inline-flex items-center gap-1 text-[9px] text-[var(--ivory-text-3)]">
          {riskInfo.icon}
          {riskInfo.label}
        </span>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-2 mt-auto pt-2 border-t border-[var(--ivory-border)]/40">
        <a
          href={skill.url}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--ivory-accent)] hover:underline cursor-pointer"
          data-testid="skill-source-link"
        >
          <ExternalLink size={10} />
          Source
        </a>
        <button
          type="button"
          onClick={onCopyLink}
          className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] transition-colors cursor-pointer"
          title="Copy source link"
        >
          <Copy size={10} />
          Copy link
        </button>
        <button
          type="button"
          onClick={onAdapt}
          disabled={isAdapting}
          className="ml-auto inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-[var(--ivory-accent-light)] text-[var(--ivory-accent)] hover:bg-[var(--ivory-accent-light)]/80 text-[10px] font-semibold transition-colors cursor-pointer disabled:opacity-50"
        >
          <ArrowRight size={10} />
          Adapt
        </button>
      </div>
    </div>
  )
}

/** Curated (Aureon-original) skill card */
function CuratedSkillCard({
  skill,
  onAdapt,
  isAdapting,
}: {
  skill: CuratedSkill
  onAdapt: () => void
  isAdapting: boolean
}): React.ReactElement {
  const catInfo = SKILL_CATEGORIES.find(c => c.id === skill.category)
  const statusColors = {
    active: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    planned: 'bg-amber-50 text-amber-700 border-amber-200',
    placeholder: 'bg-[var(--ivory-surface)] text-[var(--ivory-text-3)] border-[var(--ivory-border)]',
  }

  return (
    <div className="rounded-2xl border border-[var(--ivory-accent)]/15 bg-[var(--ivory-elevated)] shadow-[var(--shadow-md)] p-5 flex flex-col gap-3 ring-1 ring-[var(--ivory-accent)]/5" data-testid="curated-skill-card">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5 mb-1">
            <Sparkles size={13} className="text-[var(--ivory-accent)]" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-accent)]">Aureon</span>
          </div>
          <h3 className="text-[14px] font-semibold text-[var(--ivory-text)]">{skill.name}</h3>
          <span className="text-[10px] text-[var(--ivory-text-3)]">{catInfo?.label || skill.category}</span>
        </div>
        <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-semibold border ${statusColors[skill.status]}`}>
          {skill.status === 'active' ? <CheckCircle size={9} /> : skill.status === 'planned' ? <Clock size={9} /> : <AlertTriangle size={9} />}
          {skill.status}
        </span>
      </div>

      {/* Description */}
      <p className="text-[11px] text-[var(--ivory-text-2)] leading-relaxed">{skill.description}</p>

      {/* Capabilities */}
      {skill.capabilities.length > 0 && (
        <div className="space-y-1">
          <span className="text-[9px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)]">Capabilities</span>
          <ul className="space-y-0.5">
            {skill.capabilities.slice(0, 4).map((cap, i) => (
              <li key={i} className="text-[10px] text-[var(--ivory-text-2)] flex items-start gap-1.5">
                <CheckCircle size={9} className="text-emerald-500 shrink-0 mt-0.5" />
                {cap}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Inspired by */}
      <p className="text-[9px] text-[var(--ivory-text-3)] italic">
        Inspired by <a href={skill.inspiredByUrl} target="_blank" rel="noopener noreferrer" className="text-[var(--ivory-accent)] hover:underline">{skill.inspiredBy}</a>
      </p>

      {/* Actions */}
      <div className="flex items-center gap-2 mt-auto pt-2 border-t border-[var(--ivory-border)]/40">
        {skill.status === 'active' && (
          <button
            type="button"
            onClick={onAdapt}
            disabled={isAdapting}
            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-[var(--ivory-accent)] text-white hover:bg-[var(--ivory-accent-hover)] text-[10px] font-semibold transition-colors cursor-pointer disabled:opacity-50"
          >
            <Zap size={10} />
            Use Skill
          </button>
        )}
        {skill.status === 'planned' && (
          <span className="text-[10px] font-medium text-[var(--ivory-text-3)] px-3 py-1.5 rounded-full bg-[var(--ivory-surface)] border border-[var(--ivory-border)]">
            Coming soon
          </span>
        )}
        {skill.status === 'placeholder' && (
          <span className="text-[10px] font-medium text-[var(--ivory-text-3)] px-3 py-1.5 rounded-full bg-[var(--ivory-surface)] border border-dashed border-[var(--ivory-border)]">
            Placeholder
          </span>
        )}
      </div>
    </div>
  )
}

/** Adapt skill flow — shows prompt/plan for creating an Aureon version */
function AdaptFlowModal({
  skillId,
  onClose,
}: {
  skillId: string
  onClose: () => void
}): React.ReactElement {
  const [copied, setCopied] = useState(false)

  const adaptPrompt = `Create an original Aureon Desk skill inspired by external skill "${skillId}".

Requirements:
1. Write an original SKILL.md following Aureon skill conventions
2. Use the Aureon calm ivory design system (#FAF7F2, #C75B39, Inter font, serif headings)
3. Define clear capabilities, permissions, and usage examples
4. Do NOT copy content from the external source — create an original implementation
5. Include a "Inspired by" section with attribution to the source
6. Add "Adapted for Aureon Desk" badge

The skill should be production-quality and follow security best practices.`

  const handleCopy = () => {
    navigator.clipboard?.writeText(adaptPrompt).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20" onClick={onClose}>
      <div
        className="bg-[var(--ivory-elevated)] border border-[var(--ivory-border)] rounded-[24px] shadow-[var(--shadow-xl)] p-6 max-w-lg w-full mx-4 max-h-[80vh] overflow-y-auto"
        onClick={e => e.stopPropagation()}
        data-testid="adapt-skill-modal"
      >
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-[15px] font-semibold text-[var(--ivory-text)] flex items-center gap-2">
            <Lightbulb size={16} className="text-[var(--ivory-accent)]" />
            Adapt into Aureon Skill
          </h3>
          <button type="button" onClick={onClose} className="p-1 text-[var(--ivory-text-3)] hover:text-[var(--ivory-text)] cursor-pointer">
            <X size={16} />
          </button>
        </div>

        <div className="space-y-4">
          <div className="p-3 rounded-xl bg-amber-50/40 border border-amber-200/30">
            <div className="flex gap-2 items-start">
              <AlertTriangle size={13} className="text-amber-600/70 shrink-0 mt-0.5" />
              <div className="text-[10px] leading-relaxed text-amber-800/80">
                <span className="font-semibold">Original content only.</span> The adaptation creates an original Aureon skill inspired by "{skillId}" — it does NOT copy the source content. External skills may have different licenses; verify before use.
              </div>
            </div>
          </div>

          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--ivory-text-3)] block mb-1.5">Adaptation Prompt</span>
            <div className="rounded-xl border border-[var(--ivory-border)] bg-[var(--ivory-bg)] p-3">
              <pre className="text-[11px] font-mono text-[var(--ivory-text-2)] leading-relaxed whitespace-pre-wrap break-all">{adaptPrompt}</pre>
            </div>
          </div>

          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[var(--ivory-accent)] text-white hover:bg-[var(--ivory-accent-hover)] text-[11px] font-semibold transition-colors cursor-pointer"
            >
              {copied ? <CheckCircle size={12} /> : <Copy size={12} />}
              {copied ? 'Copied!' : 'Copy to composer'}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-[var(--ivory-border)] text-[var(--ivory-text-2)] hover:text-[var(--ivory-text)] text-[11px] font-semibold transition-colors cursor-pointer"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
