#!/usr/bin/env node
/**
 * Vibeforge — Self-Test Coding Agent Demo
 * 
 * Generates the "Vibeforge Counter Demo" sandbox, starts the preview server,
 * and verifies the output with a simple HTTP check.
 * 
 * Usage: node scripts/demo-coding.mjs
 * 
 * Safety: runs only in a sandbox directory under a temp folder.
 * No external APIs, no secrets, no network calls except localhost.
 */

import { createServer } from 'http'
import { readFileSync, existsSync, rmSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { tmpdir } from 'os'
import { randomBytes } from 'crypto'
import { spawn } from 'child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')

// ── Demo Counter HTML (same as in live-preview.service.ts) ──────

const DEMO_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vibeforge Counter Demo</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      background: #FAF8F5;
      color: #2C2416;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; padding: 2rem;
    }
    .card {
      background: white;
      border-radius: 16px;
      padding: 2.5rem;
      box-shadow: 0 4px 32px rgba(44,36,22,0.08);
      max-width: 400px; width: 100%; text-align: center;
    }
    h1 {
      font-size: 1.75rem;
      margin-bottom: 0.25rem;
      color: #C75B39;
      letter-spacing: -0.02em;
    }
    .subtitle {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.8rem;
      color: #8B7E6A;
      margin-bottom: 1.5rem;
      font-style: italic;
    }
    .counter {
      font-size: 3rem;
      font-weight: bold;
      color: #2C2416;
      margin: 1.25rem 0;
      font-variant-numeric: tabular-nums;
      user-select: none;
    }
    .btn-row { display: flex; gap: 0.75rem; justify-content: center; flex-wrap: wrap; }
    .btn {
      border: none; border-radius: 8px;
      padding: 0.6rem 1.5rem; cursor: pointer;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.875rem; font-weight: 500;
      transition: background 0.15s, transform 0.1s;
    }
    .btn:active { transform: scale(0.97); }
    .btn-inc { background: #C75B39; color: white; }
    .btn-inc:hover { background: #B04D2E; }
    .btn-reset { background: #EDE4D8; color: #5C4A3A; }
    .btn-reset:hover { background: #D9CDBE; }
    .footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid #EDE4D8;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 0.7rem;
      color: #A89880;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>Vibeforge Counter Demo</h1>
    <p class="subtitle">Self-Test Coding Agent Demo</p>
    <div class="counter" id="counter">0</div>
    <div class="btn-row">
      <button class="btn btn-inc" id="btn-increment" onclick="increment()">Increment</button>
      <button class="btn btn-reset" id="btn-reset" onclick="reset()">Reset</button>
    </div>
    <p class="footer">Generated by Vibeforge</p>
  </div>
  <script>
    let count = 0;
    const counterEl = document.getElementById('counter');
    function increment() {
      count++;
      counterEl.textContent = count;
      counterEl.classList.add('bump');
      setTimeout(function() { counterEl.classList.remove('bump'); }, 150);
    }
    function reset() {
      count = 0;
      counterEl.textContent = count;
    }
  </script>
</body>
</html>`

import net from 'net'
import http from 'http'

// ── Helpers ─────────────────────────────────────────────────────

function findAvailablePort(start = 3100) {
  for (let offset = 0; offset < 100; offset++) {
    const port = start + offset
    try {
      const server = new net.Server()
      server.listen(port, '127.0.0.1')
      server.close()
      return port
    } catch { /* busy */ }
  }
  const server = new net.Server()
  server.listen(0, '127.0.0.1')
  const p = server.address().port
  server.close()
  return p
}

function httpGet(url) {
  return new Promise((resolve, reject) => {
    http.get(url, (res) => {
      let data = ''
      res.on('data', chunk => data += chunk)
      res.on('end', () => resolve({ status: res.statusCode, body: data }))
    }).on('error', reject)
  })
}

// ── Main ────────────────────────────────────────────────────────

async function main() {
  const startTime = Date.now()
  const sandboxId = randomBytes(8).toString('hex')
  const sandboxDir = join(tmpdir(), `vibeforge-demo-${sandboxId}`)
  const port = findAvailablePort()

  console.log('╔══════════════════════════════════════╗')
  console.log('║  Vibeforge — Coding Agent Demo      ║')
  console.log('╚══════════════════════════════════════╝')
  console.log()
  console.log(`Sandbox:  ${sandboxDir}`)
  console.log(`Port:     ${port}`)
  console.log()

  try {
    // Step 1: Write demo files
    const { mkdirSync, writeFileSync } = await import('fs')
    mkdirSync(sandboxDir, { recursive: true })
    writeFileSync(join(sandboxDir, 'index.html'), DEMO_HTML, 'utf-8')
    console.log('✅ Files written: index.html')

    // Step 2: Start local server
    const serverScript = `
const http = require('http');
const fs = require('fs');
const path = require('path');
const root = ${JSON.stringify(sandboxDir)};

function getCT(fp) {
  const t={'.html':'text/html','.js':'application/javascript','.css':'text/css'};
  return t[path.extname(fp).toLowerCase()]||'text/plain';
}

const srv = http.createServer((req, res) => {
  let fp = path.join(root, req.url === '/' ? 'index.html' : req.url.split('?')[0]);
  if (!fp.startsWith(root)) { res.writeHead(403); res.end('Forbidden'); return; }
  try {
    if (fs.existsSync(fp) && fs.statSync(fp).isFile()) {
      res.writeHead(200, { 'Content-Type': getCT(fp), 'Access-Control-Allow-Origin': '*' });
      res.end(fs.readFileSync(fp));
    } else { res.writeHead(404); res.end('Not found'); }
  } catch(e) { res.writeHead(500); res.end('Server error'); }
});

srv.listen(${port}, '127.0.0.1', () => {
  console.log('Vibeforge_PREVIEW_READY:' + ${port});
});
srv.on('error', (e) => { console.error('Vibeforge_PREVIEW_ERROR:' + e.message); process.exit(1); });
`

    const proc = spawn(process.execPath, ['-e', serverScript], {
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    // Wait for readiness
    const ready = await new Promise((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Server start timeout (10s)')), 10000)
      proc.stdout.on('data', (d) => {
        const t = d.toString()
        if (t.includes('Vibeforge_PREVIEW_READY')) {
          clearTimeout(timeout)
          resolve(parseInt(t.split(':')[1]))
        }
      })
      proc.stderr.on('data', (d) => process.stderr.write(`[server] ${d}`))
      proc.on('error', (e) => { clearTimeout(timeout); reject(e) })
    })

    console.log(`✅ Server started on port ${ready}`)
    const url = `http://127.0.0.1:${port}`

    // Step 3: Verify response
    const resp = await httpGet(url)
    const body = resp.body

    const checks = {
      statusOk: resp.status === 200,
      titleMatches: body.includes('Vibeforge Counter Demo'),
      counterPresent: body.includes('id="counter"'),
      incrementBtn: body.includes('id="btn-increment"'),
      resetBtn: body.includes('id="btn-reset"'),
      footerText: body.includes('Generated by Vibeforge'),
      scriptPresent: body.includes('function increment()'),
      scriptResetPresent: body.includes('function reset()'),
      noSecrets: !body.includes('sk-') && !body.includes('AIza') && !body.includes('Bearer'),
    }

    console.log()
    console.log('🔍 Verification:')
    for (const [check, passed] of Object.entries(checks)) {
      console.log(`   ${passed ? '✅' : '❌'} ${check}`)
    }

    const allPassed = Object.values(checks).every(Boolean)
    const elapsed = Date.now() - startTime

    // Step 4: Cleanup
    proc.kill('SIGTERM')
    setTimeout(() => { try { proc.kill('SIGKILL') } catch {} }, 1000)

    try { rmSync(sandboxDir, { recursive: true, force: true }) } catch {}

    console.log()
    console.log(`⏱  Elapsed: ${elapsed}ms`)
    console.log()
    if (allPassed) {
      console.log('🎉 RESULT: PASS — Vibeforge Counter Demo verified successfully!')
      process.exit(0)
    } else {
      console.log('❌ RESULT: FAIL — Some checks did not pass.')
      process.exit(1)
    }

  } catch (err) {
    console.error(`❌ ERROR: ${err.message}`)
    try { rmSync(sandboxDir, { recursive: true, force: true }) } catch {}
    process.exit(1)
  }
}

main()
